-- Insertar Aeropuertos
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ABE', 'Lehigh Valley International Airport (Allentown, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ABQ', 'Albuquerque International Sunport (Albuquerque, NM)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ABY', 'Southwest Georgia Regional Airport (Albany, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ACK', 'Nantucket Memorial Airport (Nantucket, MA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ADK', 'Adak Airport (Adak, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ADQ', 'Kodiak Airport (Kodiak, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AEX', 'Alexandria International Airport (Alexandria, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AGS', 'Augusta Regional Airport (Augusta, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AKN', 'King Salmon Airport (King Salmon, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ALB', 'Albany International Airport (Albany, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AMA', 'Rick Husband Amarillo International Airport (Amarillo, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ANC', 'Ted Stevens Anchorage International Airport (Anchorage, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ATL', 'Hartsfield-Jackson Atlanta International Airport (Atlanta, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ATW', 'Appleton International Airport (Appleton, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AUS', 'Austin-Bergstrom International Airport (Austin, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AVL', 'Asheville Regional Airport (Asheville, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AVP', 'Wilkes-Barre/Scranton International Airport (Wilkes-Barre, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('AZO', 'Kalamazoo/Battle Creek International Airport (Kalamazoo, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BDL', 'Bradley International Airport (Hartford/Springfield, CT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BET', 'Bethel Airport (Bethel, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BFL', 'Meadows Field (Bakersfield, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BGM', 'Greater Binghamton Airport (Binghamton, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BGR', 'Bangor International Airport (Bangor, ME)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BHM', 'Birmingham-Shuttlesworth International Airport (Birmingham, AL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BIL', 'Billings Logan International Airport (Billings, MT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BIS', 'Bismarck Municipal Airport (Bismarck, ND)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BMI', 'Central Illinois Regional Airport (Bloomington, IL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BNA', 'Nashville International Airport (Nashville, TN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BOI', 'Boise Airport (Boise, ID)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BOS', 'Boston Logan International Airport (Boston, MA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BQK', 'Brunswick Golden Isles Airport (Brunswick, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BQN', 'Rafael Hernández Airport (Aguadilla, PR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BRO', 'Brownsville/South Padre Island International Airport (Brownsville, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BRW', 'Wiley Post-Will Rogers Memorial Airport (Utqiaġvik/Barrow, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BTR', 'Baton Rouge Metropolitan Airport (Baton Rouge, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BTV', 'Burlington International Airport (Burlington, VT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BUF', 'Buffalo Niagara International Airport (Buffalo, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BUR', 'Hollywood Burbank Airport (Burbank, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport (Baltimore, MD)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('BZN', 'Bozeman Yellowstone International Airport (Bozeman, MT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CAE', 'Columbia Metropolitan Airport (Columbia, SC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CDV', 'Merle K. (Mudhole) Smith Airport (Cordova, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CHA', 'Chattanooga Metropolitan Airport (Chattanooga, TN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CHO', 'Charlottesville-Albemarle Airport (Charlottesville, VA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CHS', 'Charleston International Airport (Charleston, SC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CID', 'The Eastern Iowa Airport (Cedar Rapids, IA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CLE', 'Cleveland Hopkins International Airport (Cleveland, OH)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CLL', 'Easterwood Airport (College Station, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CLT', 'Charlotte Douglas International Airport (Charlotte, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CMH', 'John Glenn Columbus International Airport (Columbus, OH)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('COD', 'Yellowstone Regional Airport (Cody, WY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('COS', 'Colorado Springs Airport (Colorado Springs, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CPR', 'Casper-Natrona County International Airport (Casper, WY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CRP', 'Corpus Christi International Airport (Corpus Christi, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CRW', 'Yeager Airport (Charleston, WV)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CSG', 'Columbus Metropolitan Airport (Columbus, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CVG', 'Cincinnati/Northern Kentucky International Airport (Cincinnati, OH)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('CWA', 'Central Wisconsin Airport (Wausau, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DAB', 'Daytona Beach International Airport (Daytona Beach, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DAL', 'Dallas Love Field (Dallas, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DAY', 'Dayton International Airport (Dayton, OH)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DCA', 'Ronald Reagan Washington National Airport (Washington, DC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DEN', 'Denver International Airport (Denver, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DFW', 'Dallas/Fort Worth International Airport (Dallas/Fort Worth, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DHN', 'Dothan Regional Airport (Dothan, AL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DIK', 'Dickinson Theodore Roosevelt Regional Airport (Dickinson, ND)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DLG', 'Dillingham Airport (Dillingham, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DLH', 'Duluth International Airport (Duluth, MN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DRO', 'Durango-La Plata County Airport (Durango, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DSM', 'Des Moines International Airport (Des Moines, IA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('DTW', 'Detroit Metropolitan Wayne County Airport (Detroit, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ECP', 'Northwest Florida Beaches International Airport (Panama City, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('EGE', 'Eagle County Regional Airport (Vail/Eagle, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ELP', 'El Paso International Airport (El Paso, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('EUG', 'Eugene Airport (Eugene, OR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('EVV', 'Evansville Regional Airport (Evansville, IN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('EWR', 'Newark Liberty International Airport (Newark, NJ)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('EYW', 'Key West International Airport (Key West, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FAI', 'Fairbanks International Airport (Fairbanks, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FAR', 'Hector International Airport (Fargo, ND)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FAT', 'Fresno Yosemite International Airport (Fresno, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FAY', 'Fayetteville Regional Airport (Fayetteville, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FCA', 'Glacier Park International Airport (Kalispell, MT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FLG', 'Flagstaff Pulliam Airport (Flagstaff, AZ)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FLL', 'Fort Lauderdale-Hollywood International Airport (Fort Lauderdale, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FSD', 'Sioux Falls Regional Airport (Sioux Falls, SD)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('FWA', 'Fort Wayne International Airport (Fort Wayne, IN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GEG', 'Spokane International Airport (Spokane, WA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GFK', 'Grand Forks International Airport (Grand Forks, ND)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GJT', 'Grand Junction Regional Airport (Grand Junction, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GNV', 'Gainesville Regional Airport (Gainesville, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GPT', 'Gulfport-Biloxi International Airport (Gulfport, MS)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GRB', 'Green Bay-Austin Straubel International Airport (Green Bay, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GRR', 'Gerald R. Ford International Airport (Grand Rapids, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GSO', 'Piedmont Triad International Airport (Greensboro, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GSP', 'Greenville-Spartanburg International Airport (Greer, SC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GST', 'Gustavus Airport (Gustavus, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GTR', 'Golden Triangle Regional Airport (Columbus/Starkville, MS)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('GUC', 'Gunnison-Crested Butte Regional Airport (Gunnison, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HDN', 'Yampa Valley Airport (Hayden/Steamboat Springs, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HLN', 'Helena Regional Airport (Helena, MT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HNL', 'Daniel K. Inouye International Airport (Honolulu, HI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HOB', 'Lea County Regional Airport (Hobbs, NM)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HPN', 'Westchester County Airport (White Plains, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HRL', 'Valley International Airport (Harlingen, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HSV', 'Huntsville International Airport (Huntsville, AL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('HYA', 'Barnstable Municipal Airport (Hyannis, MA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('IAD', 'Washington Dulles International Airport (Washington, DC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('IAH', 'George Bush Intercontinental Airport (Houston, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ICT', 'Wichita Dwight D. Eisenhower National Airport (Wichita, KS)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('IDA', 'Idaho Falls Regional Airport (Idaho Falls, ID)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ILM', 'Wilmington International Airport (Wilmington, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('IND', 'Indianapolis International Airport (Indianapolis, IN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ITH', 'Ithaca Tompkins International Airport (Ithaca, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('JAC', 'Jackson Hole Airport (Jackson, WY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('JAN', 'Jackson-Medgar Wiley Evers International Airport (Jackson, MS)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('JAX', 'Jacksonville International Airport (Jacksonville, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('JFK', 'John F. Kennedy International Airport (New York, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('JNU', 'Juneau International Airport (Juneau, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('KOA', 'Ellison Onizuka Kona International Airport (Kailua-Kona, HI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('KTN', 'Ketchikan International Airport (Ketchikan, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LAN', 'Capital Region International Airport (Lansing, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LAS', 'Harry Reid International Airport (Las Vegas, NV)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LAX', 'Los Angeles International Airport (Los Angeles, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LBB', 'Lubbock Preston Smith International Airport (Lubbock, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LCH', 'Lake Charles Regional Airport (Lake Charles, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LEX', 'Blue Grass Airport (Lexington, KY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LFT', 'Lafayette Regional Airport (Lafayette, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LGA', 'LaGuardia Airport (New York, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LIH', 'Lihue Airport (Lihue, HI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LIT', 'Bill and Hillary Clinton National Airport (Little Rock, AR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LNK', 'Lincoln Airport (Lincoln, NE)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LRD', 'Laredo International Airport (Laredo, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('LSE', 'La Crosse Regional Airport (La Crosse, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MAF', 'Midland International Air and Space Port (Midland, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MBS', 'MBS International Airport (Saginaw/Midland/Bay City, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MCI', 'Kansas City International Airport (Kansas City, MO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MCO', 'Orlando International Airport (Orlando, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MDT', 'Harrisburg International Airport (Harrisburg, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MDW', 'Chicago Midway International Airport (Chicago, IL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MEM', 'Memphis International Airport (Memphis, TN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MFE', 'McAllen Miller International Airport (McAllen, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MGM', 'Montgomery Regional Airport (Montgomery, AL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MHT', 'Manchester-Boston Regional Airport (Manchester, NH)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MIA', 'Miami International Airport (Miami, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MKE', 'Milwaukee Mitchell International Airport (Milwaukee, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MLI', 'Quad City International Airport (Moline, IL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MLU', 'Monroe Regional Airport (Monroe, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MOB', 'Mobile Regional Airport (Mobile, AL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MOT', 'Minot International Airport (Minot, ND)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MQT', 'Sawyer International Airport (Marquette, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MRY', 'Monterey Regional Airport (Monterey, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MSN', 'Dane County Regional Airport (Madison, WI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MSO', 'Missoula International Airport (Missoula, MT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MSP', 'Minneapolis-St. Paul International Airport (Minneapolis, MN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MSY', 'Louis Armstrong New Orleans International Airport (New Orleans, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MTJ', 'Montrose Regional Airport (Montrose, CO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MVY', 'Martha\'s Vineyard Airport (Martha\'s Vineyard, MA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('MYR', 'Myrtle Beach International Airport (Myrtle Beach, SC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OAJ', 'Albert J. Ellis Airport (Jacksonville, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OAK', 'Oakland International Airport (Oakland, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OGG', 'Kahului Airport (Kahului, HI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OKC', 'Will Rogers World Airport (Oklahoma City, OK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OMA', 'Eppley Airfield (Omaha, NE)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OME', 'Nome Airport (Nome, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ONT', 'Ontario International Airport (Ontario, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ORD', 'O\'Hare International Airport (Chicago, IL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ORF', 'Norfolk International Airport (Norfolk, VA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ORH', 'Worcester Regional Airport (Worcester, MA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('OTZ', 'Ralph Wien Memorial Airport (Kotzebue, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PAE', 'Paine Field (Everett, WA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PBI', 'Palm Beach International Airport (West Palm Beach, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PDX', 'Portland International Airport (Portland, OR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PHL', 'Philadelphia International Airport (Philadelphia, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PHX', 'Phoenix Sky Harbor International Airport (Phoenix, AZ)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PIT', 'Pittsburgh International Airport (Pittsburgh, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PNS', 'Pensacola International Airport (Pensacola, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PSC', 'Tri-Cities Airport (Pasco, WA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PSE', 'Mercedita Airport (Ponce, PR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PSG', 'Petersburg James A. Johnson Airport (Petersburg, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PSP', 'Palm Springs International Airport (Palm Springs, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PVD', 'Rhode Island T.F. Green International Airport (Providence, RI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('PWM', 'Portland International Jetport (Portland, ME)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RAP', 'Rapid City Regional Airport (Rapid City, SD)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RDM', 'Roberts Field (Redmond, OR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RDU', 'Raleigh-Durham International Airport (Raleigh/Durham, NC)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RIC', 'Richmond International Airport (Richmond, VA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RNO', 'Reno-Tahoe International Airport (Reno, NV)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ROA', 'Roanoke-Blacksburg Regional Airport (Roanoke, VA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('ROC', 'Greater Rochester International Airport (Rochester, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RST', 'Rochester International Airport (Rochester, MN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('RSW', 'Southwest Florida International Airport (Fort Myers, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SAF', 'Santa Fe Municipal Airport (Santa Fe, NM)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SAN', 'San Diego International Airport (San Diego, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SAT', 'San Antonio International Airport (San Antonio, TX)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SAV', 'Savannah/Hilton Head International Airport (Savannah, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SBA', 'Santa Barbara Airport (Santa Barbara, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SBN', 'South Bend International Airport (South Bend, IN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SBP', 'San Luis Obispo County Regional Airport (San Luis Obispo, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SCC', 'Deadhorse Airport (Deadhorse, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SCE', 'University Park Airport (State College, PA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SDF', 'Louisville Muhammad Ali International Airport (Louisville, KY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SEA', 'Seattle-Tacoma International Airport (Seattle, WA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SFO', 'San Francisco International Airport (San Francisco, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SGF', 'Springfield-Branson National Airport (Springfield, MO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SHV', 'Shreveport Regional Airport (Shreveport, LA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SIT', 'Sitka Rocky Gutierrez Airport (Sitka, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SJC', 'Norman Y. Mineta San José International Airport (San Jose, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SJU', 'Luis Muñoz Marín International Airport (San Juan, PR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SLC', 'Salt Lake City International Airport (Salt Lake City, UT)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SMF', 'Sacramento International Airport (Sacramento, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SNA', 'John Wayne Airport (Orange County, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SRQ', 'Sarasota-Bradenton International Airport (Sarasota, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('STL', 'St. Louis Lambert International Airport (St. Louis, MO)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('STS', 'Charles M. Schulz-Sonoma County Airport (Santa Rosa, CA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('STT', 'Cyril E. King Airport (St. Thomas, USVI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('STX', 'Henry E. Rohlsen Airport (St. Croix, USVI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('SYR', 'Syracuse Hancock International Airport (Syracuse, NY)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TLH', 'Tallahassee International Airport (Tallahassee, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TPA', 'Tampa International Airport (Tampa, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TRI', 'Tri-Cities Airport (Bristol, TN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TUL', 'Tulsa International Airport (Tulsa, OK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TUS', 'Tucson International Airport (Tucson, AZ)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TVC', 'Cherry Capital Airport (Traverse City, MI)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TXK', 'Texarkana Regional Airport (Texarkana, AR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('TYS', 'McGhee Tyson Airport (Knoxville, TN)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('VLD', 'Valdosta Regional Airport (Valdosta, GA)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('VPS', 'Destin-Fort Walton Beach Airport (Valparaiso, FL)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('WRG', 'Wrangell Airport (Wrangell, AK)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('XNA', 'Northwest Arkansas National Airport (Bentonville, AR)');
INSERT IGNORE INTO aeropuertos (codigo, ciudad) VALUES ('YAK', 'Yakutat Airport (Yakutat, AK)');

-- Insertar Aerolíneas
INSERT IGNORE INTO aerolineas (codigo, nombre) VALUES ('9E', 'Endeavor Air');
INSERT IGNORE INTO aerolineas (codigo, nombre) VALUES ('AA', 'American Airlines');
INSERT IGNORE INTO aerolineas (codigo, nombre) VALUES ('AS', 'Alaska Airlines');
INSERT IGNORE INTO aerolineas (codigo, nombre) VALUES ('B6', 'JetBlue Airways');
INSERT IGNORE INTO aerolineas (codigo, nombre) VALUES ('C5', 'CommutAir');