-- ==================================================================
-- CARGA DE DATOS INICIALES (PostgreSQL Compatible)
-- ==================================================================

-- 1. Insertar Aerolíneas (Si ya existen, no hace nada)
INSERT INTO aerolineas (codigo, nombre) VALUES ('9E', 'Endeavor Air') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aerolineas (codigo, nombre) VALUES ('AA', 'American Airlines') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aerolineas (codigo, nombre) VALUES ('AS', 'Alaska Airlines') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aerolineas (codigo, nombre) VALUES ('B6', 'JetBlue Airways') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aerolineas (codigo, nombre) VALUES ('C5', 'CommutAir') ON CONFLICT (codigo) DO NOTHING;

-- 2. Insertar Aeropuertos (Si ya existen, no hace nada)
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ABE', 'Lehigh Valley International Airport (Allentown, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ABQ', 'Albuquerque International Sunport (Albuquerque, NM)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ABY', 'Southwest Georgia Regional Airport (Albany, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ACK', 'Nantucket Memorial Airport (Nantucket, MA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ADK', 'Adak Airport (Adak, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ADQ', 'Kodiak Airport (Kodiak, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AEX', 'Alexandria International Airport (Alexandria, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AGS', 'Augusta Regional Airport (Augusta, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AKN', 'King Salmon Airport (King Salmon, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ALB', 'Albany International Airport (Albany, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AMA', 'Rick Husband Amarillo International Airport (Amarillo, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ANC', 'Ted Stevens Anchorage International Airport (Anchorage, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ATL', 'Hartsfield-Jackson Atlanta International Airport (Atlanta, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ATW', 'Appleton International Airport (Appleton, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AUS', 'Austin-Bergstrom International Airport (Austin, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AVL', 'Asheville Regional Airport (Asheville, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AVP', 'Wilkes-Barre/Scranton International Airport (Wilkes-Barre, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('AZO', 'Kalamazoo/Battle Creek International Airport (Kalamazoo, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BDL', 'Bradley International Airport (Hartford/Springfield, CT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BET', 'Bethel Airport (Bethel, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BFL', 'Meadows Field (Bakersfield, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BGM', 'Greater Binghamton Airport (Binghamton, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BGR', 'Bangor International Airport (Bangor, ME)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BHM', 'Birmingham-Shuttlesworth International Airport (Birmingham, AL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BIL', 'Billings Logan International Airport (Billings, MT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BIS', 'Bismarck Municipal Airport (Bismarck, ND)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BMI', 'Central Illinois Regional Airport (Bloomington, IL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BNA', 'Nashville International Airport (Nashville, TN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BOI', 'Boise Airport (Boise, ID)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BOS', 'Boston Logan International Airport (Boston, MA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BQK', 'Brunswick Golden Isles Airport (Brunswick, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BQN', 'Rafael Hernández Airport (Aguadilla, PR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BRO', 'Brownsville/South Padre Island International Airport (Brownsville, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BRW', 'Wiley Post-Will Rogers Memorial Airport (Utqiaġvik/Barrow, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BTR', 'Baton Rouge Metropolitan Airport (Baton Rouge, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BTV', 'Burlington International Airport (Burlington, VT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BUF', 'Buffalo Niagara International Airport (Buffalo, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BUR', 'Hollywood Burbank Airport (Burbank, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport (Baltimore, MD)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('BZN', 'Bozeman Yellowstone International Airport (Bozeman, MT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CAE', 'Columbia Metropolitan Airport (Columbia, SC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CDV', 'Merle K. (Mudhole) Smith Airport (Cordova, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CHA', 'Chattanooga Metropolitan Airport (Chattanooga, TN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CHO', 'Charlottesville-Albemarle Airport (Charlottesville, VA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CHS', 'Charleston International Airport (Charleston, SC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CID', 'The Eastern Iowa Airport (Cedar Rapids, IA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CLE', 'Cleveland Hopkins International Airport (Cleveland, OH)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CLL', 'Easterwood Airport (College Station, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CLT', 'Charlotte Douglas International Airport (Charlotte, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CMH', 'John Glenn Columbus International Airport (Columbus, OH)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('COD', 'Yellowstone Regional Airport (Cody, WY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('COS', 'Colorado Springs Airport (Colorado Springs, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CPR', 'Casper-Natrona County International Airport (Casper, WY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CRP', 'Corpus Christi International Airport (Corpus Christi, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CRW', 'Yeager Airport (Charleston, WV)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CSG', 'Columbus Metropolitan Airport (Columbus, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CVG', 'Cincinnati/Northern Kentucky International Airport (Cincinnati, OH)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('CWA', 'Central Wisconsin Airport (Wausau, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DAB', 'Daytona Beach International Airport (Daytona Beach, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DAL', 'Dallas Love Field (Dallas, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DAY', 'Dayton International Airport (Dayton, OH)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DCA', 'Ronald Reagan Washington National Airport (Washington, DC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DEN', 'Denver International Airport (Denver, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DFW', 'Dallas/Fort Worth International Airport (Dallas/Fort Worth, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DHN', 'Dothan Regional Airport (Dothan, AL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DIK', 'Dickinson Theodore Roosevelt Regional Airport (Dickinson, ND)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DLG', 'Dillingham Airport (Dillingham, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DLH', 'Duluth International Airport (Duluth, MN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DRO', 'Durango-La Plata County Airport (Durango, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DSM', 'Des Moines International Airport (Des Moines, IA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('DTW', 'Detroit Metropolitan Wayne County Airport (Detroit, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ECP', 'Northwest Florida Beaches International Airport (Panama City, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('EGE', 'Eagle County Regional Airport (Vail/Eagle, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ELP', 'El Paso International Airport (El Paso, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('EUG', 'Eugene Airport (Eugene, OR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('EVV', 'Evansville Regional Airport (Evansville, IN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('EWR', 'Newark Liberty International Airport (Newark, NJ)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('EYW', 'Key West International Airport (Key West, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FAI', 'Fairbanks International Airport (Fairbanks, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FAR', 'Hector International Airport (Fargo, ND)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FAT', 'Fresno Yosemite International Airport (Fresno, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FAY', 'Fayetteville Regional Airport (Fayetteville, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FCA', 'Glacier Park International Airport (Kalispell, MT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FLG', 'Flagstaff Pulliam Airport (Flagstaff, AZ)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FLL', 'Fort Lauderdale-Hollywood International Airport (Fort Lauderdale, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FSD', 'Sioux Falls Regional Airport (Sioux Falls, SD)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('FWA', 'Fort Wayne International Airport (Fort Wayne, IN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GEG', 'Spokane International Airport (Spokane, WA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GFK', 'Grand Forks International Airport (Grand Forks, ND)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GJT', 'Grand Junction Regional Airport (Grand Junction, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GNV', 'Gainesville Regional Airport (Gainesville, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GPT', 'Gulfport-Biloxi International Airport (Gulfport, MS)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GRB', 'Green Bay-Austin Straubel International Airport (Green Bay, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GRR', 'Gerald R. Ford International Airport (Grand Rapids, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GSO', 'Piedmont Triad International Airport (Greensboro, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GSP', 'Greenville-Spartanburg International Airport (Greer, SC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GST', 'Gustavus Airport (Gustavus, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GTR', 'Golden Triangle Regional Airport (Columbus/Starkville, MS)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('GUC', 'Gunnison-Crested Butte Regional Airport (Gunnison, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HDN', 'Yampa Valley Airport (Hayden/Steamboat Springs, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HLN', 'Helena Regional Airport (Helena, MT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HNL', 'Daniel K. Inouye International Airport (Honolulu, HI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HOB', 'Lea County Regional Airport (Hobbs, NM)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HPN', 'Westchester County Airport (White Plains, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HRL', 'Valley International Airport (Harlingen, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HSV', 'Huntsville International Airport (Huntsville, AL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('HYA', 'Barnstable Municipal Airport (Hyannis, MA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('IAD', 'Washington Dulles International Airport (Washington, DC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('IAH', 'George Bush Intercontinental Airport (Houston, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ICT', 'Wichita Dwight D. Eisenhower National Airport (Wichita, KS)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('IDA', 'Idaho Falls Regional Airport (Idaho Falls, ID)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ILM', 'Wilmington International Airport (Wilmington, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('IND', 'Indianapolis International Airport (Indianapolis, IN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ITH', 'Ithaca Tompkins International Airport (Ithaca, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('JAC', 'Jackson Hole Airport (Jackson, WY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('JAN', 'Jackson-Medgar Wiley Evers International Airport (Jackson, MS)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('JAX', 'Jacksonville International Airport (Jacksonville, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('JFK', 'John F. Kennedy International Airport (New York, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('JNU', 'Juneau International Airport (Juneau, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('KOA', 'Ellison Onizuka Kona International Airport (Kailua-Kona, HI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('KTN', 'Ketchikan International Airport (Ketchikan, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LAN', 'Capital Region International Airport (Lansing, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LAS', 'Harry Reid International Airport (Las Vegas, NV)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LAX', 'Los Angeles International Airport (Los Angeles, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LBB', 'Lubbock Preston Smith International Airport (Lubbock, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LCH', 'Lake Charles Regional Airport (Lake Charles, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LEX', 'Blue Grass Airport (Lexington, KY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LFT', 'Lafayette Regional Airport (Lafayette, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LGA', 'LaGuardia Airport (New York, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LIH', 'Lihue Airport (Lihue, HI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LIT', 'Bill and Hillary Clinton National Airport (Little Rock, AR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LNK', 'Lincoln Airport (Lincoln, NE)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LRD', 'Laredo International Airport (Laredo, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('LSE', 'La Crosse Regional Airport (La Crosse, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MAF', 'Midland International Air and Space Port (Midland, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MBS', 'MBS International Airport (Saginaw/Midland/Bay City, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MCI', 'Kansas City International Airport (Kansas City, MO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MCO', 'Orlando International Airport (Orlando, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MDT', 'Harrisburg International Airport (Harrisburg, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MDW', 'Chicago Midway International Airport (Chicago, IL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MEM', 'Memphis International Airport (Memphis, TN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MFE', 'McAllen Miller International Airport (McAllen, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MGM', 'Montgomery Regional Airport (Montgomery, AL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MHT', 'Manchester-Boston Regional Airport (Manchester, NH)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MIA', 'Miami International Airport (Miami, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MKE', 'Milwaukee Mitchell International Airport (Milwaukee, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MLI', 'Quad City International Airport (Moline, IL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MLU', 'Monroe Regional Airport (Monroe, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MOB', 'Mobile Regional Airport (Mobile, AL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MOT', 'Minot International Airport (Minot, ND)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MQT', 'Sawyer International Airport (Marquette, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MRY', 'Monterey Regional Airport (Monterey, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MSN', 'Dane County Regional Airport (Madison, WI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MSO', 'Missoula International Airport (Missoula, MT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MSP', 'Minneapolis-St. Paul International Airport (Minneapolis, MN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MSY', 'Louis Armstrong New Orleans International Airport (New Orleans, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MTJ', 'Montrose Regional Airport (Montrose, CO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MVY', 'Marthas Vineyard Airport (Marthas Vineyard, MA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('MYR', 'Myrtle Beach International Airport (Myrtle Beach, SC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OAJ', 'Albert J. Ellis Airport (Jacksonville, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OAK', 'Oakland International Airport (Oakland, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OGG', 'Kahului Airport (Kahului, HI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OKC', 'Will Rogers World Airport (Oklahoma City, OK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OMA', 'Eppley Airfield (Omaha, NE)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OME', 'Nome Airport (Nome, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ONT', 'Ontario International Airport (Ontario, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ORD', 'OHare International Airport (Chicago, IL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ORF', 'Norfolk International Airport (Norfolk, VA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ORH', 'Worcester Regional Airport (Worcester, MA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('OTZ', 'Ralph Wien Memorial Airport (Kotzebue, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PAE', 'Paine Field (Everett, WA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PBI', 'Palm Beach International Airport (West Palm Beach, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PDX', 'Portland International Airport (Portland, OR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PHL', 'Philadelphia International Airport (Philadelphia, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PHX', 'Phoenix Sky Harbor International Airport (Phoenix, AZ)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PIT', 'Pittsburgh International Airport (Pittsburgh, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PNS', 'Pensacola International Airport (Pensacola, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PSC', 'Tri-Cities Airport (Pasco, WA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PSE', 'Mercedita Airport (Ponce, PR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PSG', 'Petersburg James A. Johnson Airport (Petersburg, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PSP', 'Palm Springs International Airport (Palm Springs, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PVD', 'Rhode Island T.F. Green International Airport (Providence, RI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('PWM', 'Portland International Jetport (Portland, ME)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RAP', 'Rapid City Regional Airport (Rapid City, SD)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RDM', 'Roberts Field (Redmond, OR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RDU', 'Raleigh-Durham International Airport (Raleigh/Durham, NC)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RIC', 'Richmond International Airport (Richmond, VA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RNO', 'Reno-Tahoe International Airport (Reno, NV)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ROA', 'Roanoke-Blacksburg Regional Airport (Roanoke, VA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('ROC', 'Greater Rochester International Airport (Rochester, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RST', 'Rochester International Airport (Rochester, MN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('RSW', 'Southwest Florida International Airport (Fort Myers, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SAF', 'Santa Fe Municipal Airport (Santa Fe, NM)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SAN', 'San Diego International Airport (San Diego, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SAT', 'San Antonio International Airport (San Antonio, TX)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SAV', 'Savannah/Hilton Head International Airport (Savannah, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SBA', 'Santa Barbara Airport (Santa Barbara, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SBN', 'South Bend International Airport (South Bend, IN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SBP', 'San Luis Obispo County Regional Airport (San Luis Obispo, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SCC', 'Deadhorse Airport (Deadhorse, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SCE', 'University Park Airport (State College, PA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SDF', 'Louisville Muhammad Ali International Airport (Louisville, KY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SEA', 'Seattle-Tacoma International Airport (Seattle, WA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SFO', 'San Francisco International Airport (San Francisco, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SGF', 'Springfield-Branson National Airport (Springfield, MO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SHV', 'Shreveport Regional Airport (Shreveport, LA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SIT', 'Sitka Rocky Gutierrez Airport (Sitka, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SJC', 'Norman Y. Mineta San José International Airport (San Jose, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SJU', 'Luis Muñoz Marín International Airport (San Juan, PR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SLC', 'Salt Lake City International Airport (Salt Lake City, UT)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SMF', 'Sacramento International Airport (Sacramento, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SNA', 'John Wayne Airport (Orange County, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SRQ', 'Sarasota-Bradenton International Airport (Sarasota, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('STL', 'St. Louis Lambert International Airport (St. Louis, MO)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('STS', 'Charles M. Schulz-Sonoma County Airport (Santa Rosa, CA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('STT', 'Cyril E. King Airport (St. Thomas, USVI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('STX', 'Henry E. Rohlsen Airport (St. Croix, USVI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('SYR', 'Syracuse Hancock International Airport (Syracuse, NY)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TLH', 'Tallahassee International Airport (Tallahassee, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TPA', 'Tampa International Airport (Tampa, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TRI', 'Tri-Cities Airport (Bristol, TN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TUL', 'Tulsa International Airport (Tulsa, OK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TUS', 'Tucson International Airport (Tucson, AZ)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TVC', 'Cherry Capital Airport (Traverse City, MI)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TXK', 'Texarkana Regional Airport (Texarkana, AR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('TYS', 'McGhee Tyson Airport (Knoxville, TN)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('VLD', 'Valdosta Regional Airport (Valdosta, GA)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('VPS', 'Destin-Fort Walton Beach Airport (Valparaiso, FL)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('WRG', 'Wrangell Airport (Wrangell, AK)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('XNA', 'Northwest Arkansas National Airport (Bentonville, AR)') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO aeropuertos (codigo, ciudad) VALUES ('YAK', 'Yakutat Airport (Yakutat, AK)') ON CONFLICT (codigo) DO NOTHING;

-- 3. Actualización Masiva de Coordenadas (Latitud/Longitud)
UPDATE aeropuertos SET latitud = 40.6524, longitud = -75.4404 WHERE codigo = 'ABE';
UPDATE aeropuertos SET latitud = 35.0402, longitud = -106.6092 WHERE codigo = 'ABQ';
UPDATE aeropuertos SET latitud = 31.5355, longitud = -84.1945 WHERE codigo = 'ABY';
UPDATE aeropuertos SET latitud = 41.2531, longitud = -70.0602 WHERE codigo = 'ACK';
UPDATE aeropuertos SET latitud = 51.878, longitud = -176.646 WHERE codigo = 'ADK';
UPDATE aeropuertos SET latitud = 57.75, longitud = -152.4938 WHERE codigo = 'ADQ';
UPDATE aeropuertos SET latitud = 31.3274, longitud = -92.5486 WHERE codigo = 'AEX';
UPDATE aeropuertos SET latitud = 33.3699, longitud = -81.9645 WHERE codigo = 'AGS';
UPDATE aeropuertos SET latitud = 58.6768, longitud = -156.6492 WHERE codigo = 'AKN';
UPDATE aeropuertos SET latitud = 42.7481, longitud = -73.803 WHERE codigo = 'ALB';
UPDATE aeropuertos SET latitud = 35.2194, longitud = -101.7059 WHERE codigo = 'AMA';
UPDATE aeropuertos SET latitud = 61.1743, longitud = -149.9962 WHERE codigo = 'ANC';
UPDATE aeropuertos SET latitud = 33.6407, longitud = -84.4277 WHERE codigo = 'ATL';
UPDATE aeropuertos SET latitud = 44.2574, longitud = -88.5195 WHERE codigo = 'ATW';
UPDATE aeropuertos SET latitud = 30.1975, longitud = -97.6664 WHERE codigo = 'AUS';
UPDATE aeropuertos SET latitud = 35.4362, longitud = -82.5418 WHERE codigo = 'AVL';
UPDATE aeropuertos SET latitud = 41.3382, longitud = -75.7243 WHERE codigo = 'AVP';
UPDATE aeropuertos SET latitud = 42.2349, longitud = -85.5521 WHERE codigo = 'AZO';
UPDATE aeropuertos SET latitud = 41.9389, longitud = -72.6832 WHERE codigo = 'BDL';
UPDATE aeropuertos SET latitud = 60.7798, longitud = -161.838 WHERE codigo = 'BET';
UPDATE aeropuertos SET latitud = 35.4336, longitud = -119.0568 WHERE codigo = 'BFL';
UPDATE aeropuertos SET latitud = 42.2085, longitud = -75.9796 WHERE codigo = 'BGM';
UPDATE aeropuertos SET latitud = 44.8074, longitud = -68.8281 WHERE codigo = 'BGR';
UPDATE aeropuertos SET latitud = 33.5629, longitud = -86.7535 WHERE codigo = 'BHM';
UPDATE aeropuertos SET latitud = 45.8077, longitud = -108.5429 WHERE codigo = 'BIL';
UPDATE aeropuertos SET latitud = 46.7727, longitud = -100.746 WHERE codigo = 'BIS';
UPDATE aeropuertos SET latitud = 40.4771, longitud = -88.9159 WHERE codigo = 'BMI';
UPDATE aeropuertos SET latitud = 36.1263, longitud = -86.6774 WHERE codigo = 'BNA';
UPDATE aeropuertos SET latitud = 43.5644, longitud = -116.2228 WHERE codigo = 'BOI';
UPDATE aeropuertos SET latitud = 42.3656, longitud = -71.0096 WHERE codigo = 'BOS';
UPDATE aeropuertos SET latitud = 31.2588, longitud = -81.4663 WHERE codigo = 'BQK';
UPDATE aeropuertos SET latitud = 18.495, longitud = -67.1294 WHERE codigo = 'BQN';
UPDATE aeropuertos SET latitud = 25.9068, longitud = -97.4259 WHERE codigo = 'BRO';
UPDATE aeropuertos SET latitud = 71.2854, longitud = -156.766 WHERE codigo = 'BRW';
UPDATE aeropuertos SET latitud = 30.5332, longitud = -91.1496 WHERE codigo = 'BTR';
UPDATE aeropuertos SET latitud = 44.473, longitud = -73.1503 WHERE codigo = 'BTV';
UPDATE aeropuertos SET latitud = 42.9405, longitud = -78.7322 WHERE codigo = 'BUF';
UPDATE aeropuertos SET latitud = 34.2007, longitud = -118.359 WHERE codigo = 'BUR';
UPDATE aeropuertos SET latitud = 39.1754, longitud = -76.6684 WHERE codigo = 'BWI';
UPDATE aeropuertos SET latitud = 45.7769, longitud = -111.153 WHERE codigo = 'BZN';
UPDATE aeropuertos SET latitud = 33.9388, longitud = -81.1195 WHERE codigo = 'CAE';
UPDATE aeropuertos SET latitud = 60.4918, longitud = -145.4776 WHERE codigo = 'CDV';
UPDATE aeropuertos SET latitud = 35.0353, longitud = -85.2038 WHERE codigo = 'CHA';
UPDATE aeropuertos SET latitud = 38.1386, longitud = -78.4529 WHERE codigo = 'CHO';
UPDATE aeropuertos SET latitud = 32.8986, longitud = -80.0405 WHERE codigo = 'CHS';
UPDATE aeropuertos SET latitud = 41.8847, longitud = -91.7108 WHERE codigo = 'CID';
UPDATE aeropuertos SET latitud = 41.4109, longitud = -81.8494 WHERE codigo = 'CLE';
UPDATE aeropuertos SET latitud = 30.5886, longitud = -96.3638 WHERE codigo = 'CLL';
UPDATE aeropuertos SET latitud = 35.214, longitud = -80.9431 WHERE codigo = 'CLT';
UPDATE aeropuertos SET latitud = 39.998, longitud = -82.8919 WHERE codigo = 'CMH';
UPDATE aeropuertos SET latitud = 44.5202, longitud = -109.0238 WHERE codigo = 'COD';
UPDATE aeropuertos SET latitud = 38.8058, longitud = -104.7003 WHERE codigo = 'COS';
UPDATE aeropuertos SET latitud = 42.908, longitud = -106.4645 WHERE codigo = 'CPR';
UPDATE aeropuertos SET latitud = 27.7704, longitud = -97.5012 WHERE codigo = 'CRP';
UPDATE aeropuertos SET latitud = 38.3731, longitud = -81.5932 WHERE codigo = 'CRW';
UPDATE aeropuertos SET latitud = 32.5163, longitud = -84.9389 WHERE codigo = 'CSG';
UPDATE aeropuertos SET latitud = 39.0461, longitud = -84.6621 WHERE codigo = 'CVG';
UPDATE aeropuertos SET latitud = 44.7776, longitud = -89.6668 WHERE codigo = 'CWA';
UPDATE aeropuertos SET latitud = 29.1799, longitud = -81.058 WHERE codigo = 'DAB';
UPDATE aeropuertos SET latitud = 32.8471, longitud = -96.8518 WHERE codigo = 'DAL';
UPDATE aeropuertos SET latitud = 39.9024, longitud = -84.2194 WHERE codigo = 'DAY';
UPDATE aeropuertos SET latitud = 38.8512, longitud = -77.0402 WHERE codigo = 'DCA';
UPDATE aeropuertos SET latitud = 39.8561, longitud = -104.6737 WHERE codigo = 'DEN';
UPDATE aeropuertos SET latitud = 32.8998, longitud = -97.0403 WHERE codigo = 'DFW';
UPDATE aeropuertos SET latitud = 31.3213, longitud = -85.4496 WHERE codigo = 'DHN';
UPDATE aeropuertos SET latitud = 46.7974, longitud = -102.802 WHERE codigo = 'DIK';
UPDATE aeropuertos SET latitud = 59.0447, longitud = -158.5033 WHERE codigo = 'DLG';
UPDATE aeropuertos SET latitud = 46.8421, longitud = -92.1936 WHERE codigo = 'DLH';
UPDATE aeropuertos SET latitud = 37.1515, longitud = -107.7538 WHERE codigo = 'DRO';
UPDATE aeropuertos SET latitud = 41.534, longitud = -93.6631 WHERE codigo = 'DSM';
UPDATE aeropuertos SET latitud = 42.2121, longitud = -83.3533 WHERE codigo = 'DTW';
UPDATE aeropuertos SET latitud = 30.3571, longitud = -85.7955 WHERE codigo = 'ECP';
UPDATE aeropuertos SET latitud = 39.6426, longitud = -106.9177 WHERE codigo = 'EGE';
UPDATE aeropuertos SET latitud = 31.8072, longitud = -106.3776 WHERE codigo = 'ELP';
UPDATE aeropuertos SET latitud = 44.1233, longitud = -123.2187 WHERE codigo = 'EUG';
UPDATE aeropuertos SET latitud = 38.0385, longitud = -87.5306 WHERE codigo = 'EVV';
UPDATE aeropuertos SET latitud = 40.6895, longitud = -74.1745 WHERE codigo = 'EWR';
UPDATE aeropuertos SET latitud = 24.5561, longitud = -81.7596 WHERE codigo = 'EYW';
UPDATE aeropuertos SET latitud = 64.8137, longitud = -147.8597 WHERE codigo = 'FAI';
UPDATE aeropuertos SET latitud = 46.9193, longitud = -96.8111 WHERE codigo = 'FAR';
UPDATE aeropuertos SET latitud = 36.7762, longitud = -119.7181 WHERE codigo = 'FAT';
UPDATE aeropuertos SET latitud = 34.9912, longitud = -78.88 WHERE codigo = 'FAY';
UPDATE aeropuertos SET latitud = 48.3114, longitud = -114.2551 WHERE codigo = 'FCA';
UPDATE aeropuertos SET latitud = 35.1385, longitud = -111.6708 WHERE codigo = 'FLG';
UPDATE aeropuertos SET latitud = 26.0726, longitud = -80.1527 WHERE codigo = 'FLL';
UPDATE aeropuertos SET latitud = 43.582, longitud = -96.7419 WHERE codigo = 'FSD';
UPDATE aeropuertos SET latitud = 40.9785, longitud = -85.1951 WHERE codigo = 'FWA';
UPDATE aeropuertos SET latitud = 47.619, longitud = -117.5352 WHERE codigo = 'GEG';
UPDATE aeropuertos SET latitud = 47.9493, longitud = -97.1761 WHERE codigo = 'GFK';
UPDATE aeropuertos SET latitud = 39.1224, longitud = -108.5288 WHERE codigo = 'GJT';
UPDATE aeropuertos SET latitud = 29.6901, longitud = -82.2718 WHERE codigo = 'GNV';
UPDATE aeropuertos SET latitud = 30.4073, longitud = -89.0701 WHERE codigo = 'GPT';
UPDATE aeropuertos SET latitud = 44.4851, longitud = -88.1296 WHERE codigo = 'GRB';
UPDATE aeropuertos SET latitud = 42.8808, longitud = -85.5228 WHERE codigo = 'GRR';
UPDATE aeropuertos SET latitud = 36.0978, longitud = -79.9373 WHERE codigo = 'GSO';
UPDATE aeropuertos SET latitud = 34.8957, longitud = -82.2189 WHERE codigo = 'GSP';
UPDATE aeropuertos SET latitud = 58.4253, longitud = -135.7073 WHERE codigo = 'GST';
UPDATE aeropuertos SET latitud = 33.4503, longitud = -88.5914 WHERE codigo = 'GTR';
UPDATE aeropuertos SET latitud = 38.5339, longitud = -106.9331 WHERE codigo = 'GUC';
UPDATE aeropuertos SET latitud = 40.4812, longitud = -107.2177 WHERE codigo = 'HDN';
UPDATE aeropuertos SET latitud = 46.6068, longitud = -111.9659 WHERE codigo = 'HLN';
UPDATE aeropuertos SET latitud = 21.3187, longitud = -157.9213 WHERE codigo = 'HNL';
UPDATE aeropuertos SET latitud = 32.6875, longitud = -103.217 WHERE codigo = 'HOB';
UPDATE aeropuertos SET latitud = 41.067, longitud = -73.7076 WHERE codigo = 'HPN';
UPDATE aeropuertos SET latitud = 26.2285, longitud = -97.6544 WHERE codigo = 'HRL';
UPDATE aeropuertos SET latitud = 34.6404, longitud = -86.7751 WHERE codigo = 'HSV';
UPDATE aeropuertos SET latitud = 41.6693, longitud = -70.2804 WHERE codigo = 'HYA';
UPDATE aeropuertos SET latitud = 38.9445, longitud = -77.4558 WHERE codigo = 'IAD';
UPDATE aeropuertos SET latitud = 29.9805, longitud = -95.3397 WHERE codigo = 'IAH';
UPDATE aeropuertos SET latitud = 37.6499, longitud = -97.4331 WHERE codigo = 'ICT';
UPDATE aeropuertos SET latitud = 43.5123, longitud = -112.0702 WHERE codigo = 'IDA';
UPDATE aeropuertos SET latitud = 34.2706, longitud = -77.9026 WHERE codigo = 'ILM';
UPDATE aeropuertos SET latitud = 39.7173, longitud = -86.2944 WHERE codigo = 'IND';
UPDATE aeropuertos SET latitud = 42.491, longitud = -76.4587 WHERE codigo = 'ITH';
UPDATE aeropuertos SET latitud = 43.6073, longitud = -110.7377 WHERE codigo = 'JAC';
UPDATE aeropuertos SET latitud = 32.3112, longitud = -90.0759 WHERE codigo = 'JAN';
UPDATE aeropuertos SET latitud = 30.4941, longitud = -81.6879 WHERE codigo = 'JAX';
UPDATE aeropuertos SET latitud = 40.6413, longitud = -73.7781 WHERE codigo = 'JFK';
UPDATE aeropuertos SET latitud = 58.3547, longitud = -134.5763 WHERE codigo = 'JNU';
UPDATE aeropuertos SET latitud = 19.7388, longitud = -156.0463 WHERE codigo = 'KOA';
UPDATE aeropuertos SET latitud = 55.3556, longitud = -131.7137 WHERE codigo = 'KTN';
UPDATE aeropuertos SET latitud = 42.7787, longitud = -84.5874 WHERE codigo = 'LAN';
UPDATE aeropuertos SET latitud = 36.084, longitud = -115.1537 WHERE codigo = 'LAS';
UPDATE aeropuertos SET latitud = 33.9416, longitud = -118.4085 WHERE codigo = 'LAX';
UPDATE aeropuertos SET latitud = 33.6636, longitud = -101.8228 WHERE codigo = 'LBB';
UPDATE aeropuertos SET latitud = 30.1261, longitud = -93.2234 WHERE codigo = 'LCH';
UPDATE aeropuertos SET latitud = 38.0365, longitud = -84.6059 WHERE codigo = 'LEX';
UPDATE aeropuertos SET latitud = 30.2053, longitud = -91.9877 WHERE codigo = 'LFT';
UPDATE aeropuertos SET latitud = 40.7769, longitud = -73.874 WHERE codigo = 'LGA';
UPDATE aeropuertos SET latitud = 21.976, longitud = -159.339 WHERE codigo = 'LIH';
UPDATE aeropuertos SET latitud = 34.7294, longitud = -92.2243 WHERE codigo = 'LIT';
UPDATE aeropuertos SET latitud = 40.851, longitud = -96.7592 WHERE codigo = 'LNK';
UPDATE aeropuertos SET latitud = 27.5437, longitud = -99.4615 WHERE codigo = 'LRD';
UPDATE aeropuertos SET latitud = 43.8794, longitud = -91.2565 WHERE codigo = 'LSE';
UPDATE aeropuertos SET latitud = 31.9425, longitud = -102.2019 WHERE codigo = 'MAF';
UPDATE aeropuertos SET latitud = 43.5329, longitud = -84.0797 WHERE codigo = 'MBS';
UPDATE aeropuertos SET latitud = 39.2976, longitud = -94.7139 WHERE codigo = 'MCI';
UPDATE aeropuertos SET latitud = 28.4289, longitud = -81.316 WHERE codigo = 'MCO';
UPDATE aeropuertos SET latitud = 40.1932, longitud = -76.7634 WHERE codigo = 'MDT';
UPDATE aeropuertos SET latitud = 41.786, longitud = -87.7524 WHERE codigo = 'MDW';
UPDATE aeropuertos SET latitud = 35.0424, longitud = -89.9767 WHERE codigo = 'MEM';
UPDATE aeropuertos SET latitud = 26.1758, longitud = -98.2386 WHERE codigo = 'MFE';
UPDATE aeropuertos SET latitud = 32.3006, longitud = -86.3939 WHERE codigo = 'MGM';
UPDATE aeropuertos SET latitud = 42.9346, longitud = -71.4371 WHERE codigo = 'MHT';
UPDATE aeropuertos SET latitud = 25.7959, longitud = -80.287 WHERE codigo = 'MIA';
UPDATE aeropuertos SET latitud = 42.9472, longitud = -87.8966 WHERE codigo = 'MKE';
UPDATE aeropuertos SET latitud = 41.4485, longitud = -90.5075 WHERE codigo = 'MLI';
UPDATE aeropuertos SET latitud = 32.5109, longitud = -92.0377 WHERE codigo = 'MLU';
UPDATE aeropuertos SET latitud = 30.6914, longitud = -88.2428 WHERE codigo = 'MOB';
UPDATE aeropuertos SET latitud = 48.2594, longitud = -101.2803 WHERE codigo = 'MOT';
UPDATE aeropuertos SET latitud = 46.3536, longitud = -87.3954 WHERE codigo = 'MQT';
UPDATE aeropuertos SET latitud = 36.587, longitud = -121.8429 WHERE codigo = 'MRY';
UPDATE aeropuertos SET latitud = 43.1399, longitud = -89.3375 WHERE codigo = 'MSN';
UPDATE aeropuertos SET latitud = 46.9163, longitud = -114.0906 WHERE codigo = 'MSO';
UPDATE aeropuertos SET latitud = 44.8848, longitud = -93.2223 WHERE codigo = 'MSP';
UPDATE aeropuertos SET latitud = 29.9934, longitud = -90.258 WHERE codigo = 'MSY';
UPDATE aeropuertos SET latitud = 38.5089, longitud = -107.8938 WHERE codigo = 'MTJ';
UPDATE aeropuertos SET latitud = 41.393, longitud = -70.6143 WHERE codigo = 'MVY';
UPDATE aeropuertos SET latitud = 33.6797, longitud = -78.9283 WHERE codigo = 'MYR';
UPDATE aeropuertos SET latitud = 34.8292, longitud = -77.6121 WHERE codigo = 'OAJ';
UPDATE aeropuertos SET latitud = 37.7213, longitud = -122.2207 WHERE codigo = 'OAK';
UPDATE aeropuertos SET latitud = 20.8986, longitud = -156.4305 WHERE codigo = 'OGG';
UPDATE aeropuertos SET latitud = 35.3931, longitud = -97.6007 WHERE codigo = 'OKC';
UPDATE aeropuertos SET latitud = 41.3025, longitud = -95.8942 WHERE codigo = 'OMA';
UPDATE aeropuertos SET latitud = 64.5122, longitud = -165.4452 WHERE codigo = 'OME';
UPDATE aeropuertos SET latitud = 34.056, longitud = -117.6012 WHERE codigo = 'ONT';
UPDATE aeropuertos SET latitud = 41.9742, longitud = -87.9073 WHERE codigo = 'ORD';
UPDATE aeropuertos SET latitud = 36.8946, longitud = -76.2012 WHERE codigo = 'ORF';
UPDATE aeropuertos SET latitud = 42.2673, longitud = -71.8757 WHERE codigo = 'ORH';
UPDATE aeropuertos SET latitud = 66.8847, longitud = -162.5986 WHERE codigo = 'OTZ';
UPDATE aeropuertos SET latitud = 47.9063, longitud = -122.2821 WHERE codigo = 'PAE';
UPDATE aeropuertos SET latitud = 26.6832, longitud = -80.0956 WHERE codigo = 'PBI';
UPDATE aeropuertos SET latitud = 45.5887, longitud = -122.5975 WHERE codigo = 'PDX';
UPDATE aeropuertos SET latitud = 39.8719, longitud = -75.2411 WHERE codigo = 'PHL';
UPDATE aeropuertos SET latitud = 33.4343, longitud = -112.0116 WHERE codigo = 'PHX';
UPDATE aeropuertos SET latitud = 40.4915, longitud = -80.2329 WHERE codigo = 'PIT';
UPDATE aeropuertos SET latitud = 30.4733, longitud = -87.1874 WHERE codigo = 'PNS';
UPDATE aeropuertos SET latitud = 46.2647, longitud = -119.119 WHERE codigo = 'PSC';
UPDATE aeropuertos SET latitud = 18.0083, longitud = -66.563 WHERE codigo = 'PSE';
UPDATE aeropuertos SET latitud = 56.8017, longitud = -132.9461 WHERE codigo = 'PSG';
UPDATE aeropuertos SET latitud = 33.8297, longitud = -116.5067 WHERE codigo = 'PSP';
UPDATE aeropuertos SET latitud = 41.724, longitud = -71.4282 WHERE codigo = 'PVD';
UPDATE aeropuertos SET latitud = 43.6462, longitud = -70.3087 WHERE codigo = 'PWM';
UPDATE aeropuertos SET latitud = 44.0453, longitud = -103.0574 WHERE codigo = 'RAP';
UPDATE aeropuertos SET latitud = 44.2541, longitud = -121.15 WHERE codigo = 'RDM';
UPDATE aeropuertos SET latitud = 35.8776, longitud = -78.7875 WHERE codigo = 'RDU';
UPDATE aeropuertos SET latitud = 37.5052, longitud = -77.3197 WHERE codigo = 'RIC';
UPDATE aeropuertos SET latitud = 39.4986, longitud = -119.7681 WHERE codigo = 'RNO';
UPDATE aeropuertos SET latitud = 37.3255, longitud = -79.9754 WHERE codigo = 'ROA';
UPDATE aeropuertos SET latitud = 43.1189, longitud = -77.6724 WHERE codigo = 'ROC';
UPDATE aeropuertos SET latitud = 43.9088, longitud = -92.498 WHERE codigo = 'RST';
UPDATE aeropuertos SET latitud = 26.5362, longitud = -81.7552 WHERE codigo = 'RSW';
UPDATE aeropuertos SET latitud = 35.6171, longitud = -106.0894 WHERE codigo = 'SAF';
UPDATE aeropuertos SET latitud = 32.7336, longitud = -117.1897 WHERE codigo = 'SAN';
UPDATE aeropuertos SET latitud = 29.5337, longitud = -98.4698 WHERE codigo = 'SAT';
UPDATE aeropuertos SET latitud = 32.1276, longitud = -81.2021 WHERE codigo = 'SAV';
UPDATE aeropuertos SET latitud = 34.4262, longitud = -119.8404 WHERE codigo = 'SBA';
UPDATE aeropuertos SET latitud = 41.7087, longitud = -86.3173 WHERE codigo = 'SBN';
UPDATE aeropuertos SET latitud = 35.2371, longitud = -120.6425 WHERE codigo = 'SBP';
UPDATE aeropuertos SET latitud = 70.1947, longitud = -148.4652 WHERE codigo = 'SCC';
UPDATE aeropuertos SET latitud = 40.8512, longitud = -77.8463 WHERE codigo = 'SCE';
UPDATE aeropuertos SET latitud = 38.1744, longitud = -85.736 WHERE codigo = 'SDF';
UPDATE aeropuertos SET latitud = 47.4489, longitud = -122.3093 WHERE codigo = 'SEA';
UPDATE aeropuertos SET latitud = 37.619, longitud = -122.3748 WHERE codigo = 'SFO';
UPDATE aeropuertos SET latitud = 37.2443, longitud = -93.3869 WHERE codigo = 'SGF';
UPDATE aeropuertos SET latitud = 32.4466, longitud = -93.8256 WHERE codigo = 'SHV';
UPDATE aeropuertos SET latitud = 57.0471, longitud = -135.3616 WHERE codigo = 'SIT';
UPDATE aeropuertos SET latitud = 37.3619, longitud = -121.929 WHERE codigo = 'SJC';
UPDATE aeropuertos SET latitud = 18.4394, longitud = -66.0018 WHERE codigo = 'SJU';
UPDATE aeropuertos SET latitud = 40.7899, longitud = -111.9791 WHERE codigo = 'SLC';
UPDATE aeropuertos SET latitud = 38.6954, longitud = -121.5908 WHERE codigo = 'SMF';
UPDATE aeropuertos SET latitud = 33.6757, longitud = -117.8674 WHERE codigo = 'SNA';
UPDATE aeropuertos SET latitud = 27.3953, longitud = -82.5544 WHERE codigo = 'SRQ';
UPDATE aeropuertos SET latitud = 38.7477, longitud = -90.3591 WHERE codigo = 'STL';
UPDATE aeropuertos SET latitud = 38.509, longitud = -122.8129 WHERE codigo = 'STS';
UPDATE aeropuertos SET latitud = 18.3373, longitud = -64.9733 WHERE codigo = 'STT';
UPDATE aeropuertos SET latitud = 17.7019, longitud = -64.7986 WHERE codigo = 'STX';
UPDATE aeropuertos SET latitud = 43.1112, longitud = -76.1063 WHERE codigo = 'SYR';
UPDATE aeropuertos SET latitud = 30.3965, longitud = -84.3503 WHERE codigo = 'TLH';
UPDATE aeropuertos SET latitud = 27.9755, longitud = -82.5332 WHERE codigo = 'TPA';
UPDATE aeropuertos SET latitud = 36.4752, longitud = -82.4074 WHERE codigo = 'TRI';
UPDATE aeropuertos SET latitud = 36.1984, longitud = -95.8882 WHERE codigo = 'TUL';
UPDATE aeropuertos SET latitud = 32.1145, longitud = -110.9392 WHERE codigo = 'TUS';
UPDATE aeropuertos SET latitud = 44.7414, longitud = -85.5822 WHERE codigo = 'TVC';
UPDATE aeropuertos SET latitud = 33.4537, longitud = -93.991 WHERE codigo = 'TXK';
UPDATE aeropuertos SET latitud = 35.8125, longitud = -83.9929 WHERE codigo = 'TYS';
UPDATE aeropuertos SET latitud = 30.7825, longitud = -83.2767 WHERE codigo = 'VLD';
UPDATE aeropuertos SET latitud = 30.4832, longitud = -86.5254 WHERE codigo = 'VPS';
UPDATE aeropuertos SET latitud = 56.4843, longitud = -132.3698 WHERE codigo = 'WRG';
UPDATE aeropuertos SET latitud = 36.2819, longitud = -94.3068 WHERE codigo = 'XNA';
UPDATE aeropuertos SET latitud = 59.5033, longitud = -139.6602 WHERE codigo = 'YAK';
