-- ============================================
-- Insertar AEROLÍNEAS
-- (Se mantiene igual, asumiendo que esta tabla no requiere lat/long)
-- ============================================
INSERT INTO aerolineas (codigo, nombre, pais_origen, activa) VALUES
                                                                 ('9E', 'Endeavor Air', 'Estados Unidos', true),
                                                                 ('AA', 'American Airlines', 'Estados Unidos', true),
                                                                 ('AS', 'Alaska Airlines', 'Estados Unidos', true),
                                                                 ('B6', 'JetBlue Airways', 'Estados Unidos', true),
                                                                 ('C5', 'CommutAir', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Región Noreste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ABE', 'Lehigh Valley International Airport', 'Allentown', 'Estados Unidos', true, 40.6524, -75.4404),
                                                                                      ('ALB', 'Albany International Airport', 'Albany', 'Estados Unidos', true, 42.7481, -73.8029),
                                                                                      ('AVP', 'Wilkes-Barre/Scranton International Airport', 'Scranton', 'Estados Unidos', true, 41.3381, -75.7243),
                                                                                      ('BDL', 'Bradley International Airport', 'Hartford', 'Estados Unidos', true, 41.9388, -72.6832),
                                                                                      ('BGM', 'Greater Binghamton Airport', 'Binghamton', 'Estados Unidos', true, 42.2085, -75.9796),
                                                                                      ('BGR', 'Bangor International Airport', 'Bangor', 'Estados Unidos', true, 44.8074, -68.8281),
                                                                                      ('BOS', 'Logan International Airport', 'Boston', 'Estados Unidos', true, 42.3656, -71.0096),
                                                                                      ('BTV', 'Burlington International Airport', 'Burlington', 'Estados Unidos', true, 44.4730, -73.1503),
                                                                                      ('BUF', 'Buffalo Niagara International Airport', 'Buffalo', 'Estados Unidos', true, 42.9405, -78.7322),
                                                                                      ('BWI', 'Baltimore/Washington International Airport', 'Baltimore', 'Estados Unidos', true, 39.1754, -76.6682),
                                                                                      ('DCA', 'Ronald Reagan Washington National Airport', 'Washington', 'Estados Unidos', true, 38.8512, -77.0402),
                                                                                      ('EWR', 'Newark Liberty International Airport', 'Newark', 'Estados Unidos', true, 40.6895, -74.1745),
                                                                                      ('HPN', 'Westchester County Airport', 'White Plains', 'Estados Unidos', true, 41.0669, -73.7076),
                                                                                      ('IAD', 'Washington Dulles International Airport', 'Washington', 'Estados Unidos', true, 38.9531, -77.4565),
                                                                                      ('ITH', 'Ithaca Tompkins International Airport', 'Ithaca', 'Estados Unidos', true, 42.4916, -76.4587),
                                                                                      ('JFK', 'John F. Kennedy International Airport', 'New York', 'Estados Unidos', true, 40.6413, -73.7781),
                                                                                      ('LGA', 'LaGuardia Airport', 'New York', 'Estados Unidos', true, 40.7769, -73.8740),
                                                                                      ('MDT', 'Harrisburg International Airport', 'Harrisburg', 'Estados Unidos', true, 40.1932, -76.7634),
                                                                                      ('MHT', 'Manchester-Boston Regional Airport', 'Manchester', 'Estados Unidos', true, 42.9345, -71.4371),
                                                                                      ('ORH', 'Worcester Regional Airport', 'Worcester', 'Estados Unidos', true, 42.2673, -71.8757),
                                                                                      ('PHL', 'Philadelphia International Airport', 'Philadelphia', 'Estados Unidos', true, 39.8729, -75.2437),
                                                                                      ('PIT', 'Pittsburgh International Airport', 'Pittsburgh', 'Estados Unidos', true, 40.4914, -80.2328),
                                                                                      ('PVD', 'Rhode Island T.F. Green International Airport', 'Providence', 'Estados Unidos', true, 41.7240, -71.4282),
                                                                                      ('PWM', 'Portland International Jetport', 'Portland', 'Estados Unidos', true, 43.6462, -70.3087),
                                                                                      ('ROC', 'Greater Rochester International Airport', 'Rochester', 'Estados Unidos', true, 43.1189, -77.6724),
                                                                                      ('SYR', 'Syracuse Hancock International Airport', 'Syracuse', 'Estados Unidos', true, 43.1112, -76.1063),
                                                                                      ('ACK', 'Nantucket Memorial Airport', 'Nantucket', 'Estados Unidos', true, 41.2530, -70.0601),
                                                                                      ('MVY', 'Martha''s Vineyard Airport', 'Martha''s Vineyard', 'Estados Unidos', true, 41.3930, -70.6143);

-- ============================================
-- Insertar AEROPUERTOS - Región Sureste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'Estados Unidos', true, 33.6407, -84.4277),
                                                                                      ('AVL', 'Asheville Regional Airport', 'Asheville', 'Estados Unidos', true, 35.4362, -82.5418),
                                                                                      ('BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham', 'Estados Unidos', true, 33.5629, -86.7535),
                                                                                      ('BNA', 'Nashville International Airport', 'Nashville', 'Estados Unidos', true, 36.1263, -86.6774),
                                                                                      ('BTR', 'Baton Rouge Metropolitan Airport', 'Baton Rouge', 'Estados Unidos', true, 30.5332, -91.1496),
                                                                                      ('CAE', 'Columbia Metropolitan Airport', 'Columbia', 'Estados Unidos', true, 33.9388, -81.1195),
                                                                                      ('CHA', 'Chattanooga Metropolitan Airport', 'Chattanooga', 'Estados Unidos', true, 35.0353, -85.2038),
                                                                                      ('CHO', 'Charlottesville-Albemarle Airport', 'Charlottesville', 'Estados Unidos', true, 38.1386, -78.4529),
                                                                                      ('CHS', 'Charleston International Airport', 'Charleston', 'Estados Unidos', true, 32.8986, -80.0405),
                                                                                      ('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'Estados Unidos', true, 35.2144, -80.9473),
                                                                                      ('CSG', 'Columbus Airport', 'Columbus', 'Estados Unidos', true, 32.5163, -84.9389),
                                                                                      ('DAB', 'Daytona Beach International Airport', 'Daytona Beach', 'Estados Unidos', true, 29.1799, -81.0580),
                                                                                      ('DHN', 'Dothan Regional Airport', 'Dothan', 'Estados Unidos', true, 31.3213, -85.4496),
                                                                                      ('EYW', 'Key West International Airport', 'Key West', 'Estados Unidos', true, 24.5561, -81.7596),
                                                                                      ('FAY', 'Fayetteville Regional Airport', 'Fayetteville', 'Estados Unidos', true, 34.9912, -78.8803),
                                                                                      ('FLL', 'Fort Lauderdale-Hollywood International Airport', 'Fort Lauderdale', 'Estados Unidos', true, 26.0742, -80.1506),
                                                                                      ('GNV', 'Gainesville Regional Airport', 'Gainesville', 'Estados Unidos', true, 29.6901, -82.2718),
                                                                                      ('GPT', 'Gulfport-Biloxi International Airport', 'Gulfport', 'Estados Unidos', true, 30.4073, -89.0701),
                                                                                      ('GSO', 'Piedmont Triad International Airport', 'Greensboro', 'Estados Unidos', true, 36.1044, -79.9350),
                                                                                      ('GSP', 'Greenville-Spartanburg International Airport', 'Greenville', 'Estados Unidos', true, 34.8957, -82.2189),
                                                                                      ('GTR', 'Golden Triangle Regional Airport', 'Columbus', 'Estados Unidos', true, 33.4503, -88.5913),
                                                                                      ('HSV', 'Huntsville International Airport', 'Huntsville', 'Estados Unidos', true, 34.6404, -86.7751),
                                                                                      ('ILM', 'Wilmington International Airport', 'Wilmington', 'Estados Unidos', true, 34.2706, -77.9026),
                                                                                      ('JAN', 'Jackson-Medgar Wiley Evers International Airport', 'Jackson', 'Estados Unidos', true, 32.3112, -90.0759),
                                                                                      ('JAX', 'Jacksonville International Airport', 'Jacksonville', 'Estados Unidos', true, 30.4941, -81.6879),
                                                                                      ('LCH', 'Lake Charles Regional Airport', 'Lake Charles', 'Estados Unidos', true, 30.1260, -93.2234),
                                                                                      ('LEX', 'Blue Grass Airport', 'Lexington', 'Estados Unidos', true, 38.0365, -84.6059),
                                                                                      ('LFT', 'Lafayette Regional Airport', 'Lafayette', 'Estados Unidos', true, 30.2053, -91.9876),
                                                                                      ('MCO', 'Orlando International Airport', 'Orlando', 'Estados Unidos', true, 28.4312, -81.3081),
                                                                                      ('MEM', 'Memphis International Airport', 'Memphis', 'Estados Unidos', true, 35.0424, -89.9767),
                                                                                      ('MGM', 'Montgomery Regional Airport', 'Montgomery', 'Estados Unidos', true, 32.3006, -86.3939),
                                                                                      ('MIA', 'Miami International Airport', 'Miami', 'Estados Unidos', true, 25.7959, -80.2870),
                                                                                      ('MLI', 'Quad City International Airport', 'Moline', 'Estados Unidos', true, 41.4485, -90.5075),
                                                                                      ('MLU', 'Monroe Regional Airport', 'Monroe', 'Estados Unidos', true, 32.5109, -92.0377),
                                                                                      ('MOB', 'Mobile Regional Airport', 'Mobile', 'Estados Unidos', true, 30.6912, -88.2428),
                                                                                      ('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'Estados Unidos', true, 29.9911, -90.2592),
                                                                                      ('MYR', 'Myrtle Beach International Airport', 'Myrtle Beach', 'Estados Unidos', true, 33.6821, -78.9283),
                                                                                      ('OAJ', 'Albert J. Ellis Airport', 'Jacksonville', 'Estados Unidos', true, 34.8292, -77.6121),
                                                                                      ('ORF', 'Norfolk International Airport', 'Norfolk', 'Estados Unidos', true, 36.8946, -76.2012),
                                                                                      ('PBI', 'Palm Beach International Airport', 'West Palm Beach', 'Estados Unidos', true, 26.6832, -80.0956),
                                                                                      ('PNS', 'Pensacola International Airport', 'Pensacola', 'Estados Unidos', true, 30.4733, -87.1874),
                                                                                      ('RDU', 'Raleigh-Durham International Airport', 'Raleigh', 'Estados Unidos', true, 35.8801, -78.7877),
                                                                                      ('RIC', 'Richmond International Airport', 'Richmond', 'Estados Unidos', true, 37.5052, -77.3197),
                                                                                      ('ROA', 'Roanoke-Blacksburg Regional Airport', 'Roanoke', 'Estados Unidos', true, 37.3255, -79.9754),
                                                                                      ('RSW', 'Southwest Florida International Airport', 'Fort Myers', 'Estados Unidos', true, 26.5362, -81.7552),
                                                                                      ('SAV', 'Savannah/Hilton Head International Airport', 'Savannah', 'Estados Unidos', true, 32.1276, -81.2021),
                                                                                      ('SHV', 'Shreveport Regional Airport', 'Shreveport', 'Estados Unidos', true, 32.4466, -93.8256),
                                                                                      ('SRQ', 'Sarasota-Bradenton International Airport', 'Sarasota', 'Estados Unidos', true, 27.3956, -82.5544),
                                                                                      ('TLH', 'Tallahassee International Airport', 'Tallahassee', 'Estados Unidos', true, 30.3965, -84.3503),
                                                                                      ('TPA', 'Tampa International Airport', 'Tampa', 'Estados Unidos', true, 27.9772, -82.5311),
                                                                                      ('TRI', 'Tri-Cities Airport', 'Bristol', 'Estados Unidos', true, 36.4752, -82.4074),
                                                                                      ('TYS', 'McGhee Tyson Airport', 'Knoxville', 'Estados Unidos', true, 35.8125, -83.9929),
                                                                                      ('VLD', 'Valdosta Regional Airport', 'Valdosta', 'Estados Unidos', true, 30.7825, -83.2767),
                                                                                      ('VPS', 'Destin-Fort Walton Beach Airport', 'Valparaiso', 'Estados Unidos', true, 30.4832, -86.5254),
                                                                                      ('BRO', 'Brownsville/South Padre Island International Airport', 'Brownsville', 'Estados Unidos', true, 25.9068, -97.4259),
                                                                                      ('CRP', 'Corpus Christi International Airport', 'Corpus Christi', 'Estados Unidos', true, 27.7704, -97.5012),
                                                                                      ('HRL', 'Valley International Airport', 'Harlingen', 'Estados Unidos', true, 26.2285, -97.6544),
                                                                                      ('BQN', 'Rafael Hernández Airport', 'Aguadilla', 'Puerto Rico', true, 18.4949, -67.1294),
                                                                                      ('PSE', 'Mercedita Airport', 'Ponce', 'Puerto Rico', true, 18.0083, -66.5630),
                                                                                      ('SJU', 'Luis Muñoz Marín International Airport', 'San Juan', 'Puerto Rico', true, 18.4394, -66.0018),
                                                                                      ('STT', 'Cyril E. King Airport', 'Charlotte Amalie', 'Islas Vírgenes de EE.UU.', true, 18.3373, -64.9733),
                                                                                      ('STX', 'Henry E. Rohlsen Airport', 'Christiansted', 'Islas Vírgenes de EE.UU.', true, 17.7019, -64.7986),
                                                                                      ('ECP', 'Northwest Florida Beaches International Airport', 'Panama City', 'Estados Unidos', true, 30.3571, -85.7955);

-- ============================================
-- Insertar AEROPUERTOS - Región Medio Oeste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ATW', 'Appleton International Airport', 'Appleton', 'Estados Unidos', true, 44.2581, -88.5191),
                                                                                      ('AZO', 'Kalamazoo/Battle Creek International Airport', 'Kalamazoo', 'Estados Unidos', true, 42.2349, -85.5521),
                                                                                      ('BMI', 'Central Illinois Regional Airport', 'Bloomington', 'Estados Unidos', true, 40.4771, -88.9159),
                                                                                      ('CID', 'The Eastern Iowa Airport', 'Cedar Rapids', 'Estados Unidos', true, 41.8846, -91.7108),
                                                                                      ('CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'Estados Unidos', true, 41.4094, -81.8547),
                                                                                      ('CMH', 'John Glenn Columbus International Airport', 'Columbus', 'Estados Unidos', true, 39.9980, -82.8919),
                                                                                      ('CRW', 'Yeager Airport', 'Charleston', 'Estados Unidos', true, 38.3731, -81.5932),
                                                                                      ('CVG', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati', 'Estados Unidos', true, 39.0461, -84.6621),
                                                                                      ('CWA', 'Central Wisconsin Airport', 'Wausau', 'Estados Unidos', true, 44.7776, -89.6668),
                                                                                      ('DAY', 'James M. Cox Dayton International Airport', 'Dayton', 'Estados Unidos', true, 39.9024, -84.2194),
                                                                                      ('DLH', 'Duluth International Airport', 'Duluth', 'Estados Unidos', true, 46.8421, -92.1936),
                                                                                      ('DSM', 'Des Moines International Airport', 'Des Moines', 'Estados Unidos', true, 41.5340, -93.6631),
                                                                                      ('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'Estados Unidos', true, 42.2121, -83.3533),
                                                                                      ('EVV', 'Evansville Regional Airport', 'Evansville', 'Estados Unidos', true, 38.0385, -87.5306),
                                                                                      ('FAR', 'Hector International Airport', 'Fargo', 'Estados Unidos', true, 46.9193, -96.8111),
                                                                                      ('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'Estados Unidos', true, 43.5820, -96.7419),
                                                                                      ('GFK', 'Grand Forks International Airport', 'Grand Forks', 'Estados Unidos', true, 47.9493, -97.1761),
                                                                                      ('GRB', 'Green Bay-Austin Straubel International Airport', 'Green Bay', 'Estados Unidos', true, 44.4851, -88.1296),
                                                                                      ('GRR', 'Gerald R. Ford International Airport', 'Grand Rapids', 'Estados Unidos', true, 42.8808, -85.5227),
                                                                                      ('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'Estados Unidos', true, 37.6499, -97.4331),
                                                                                      ('IND', 'Indianapolis International Airport', 'Indianapolis', 'Estados Unidos', true, 39.7173, -86.2944),
                                                                                      ('LAN', 'Capital Region International Airport', 'Lansing', 'Estados Unidos', true, 42.7787, -84.5874),
                                                                                      ('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'Estados Unidos', true, 34.7294, -92.2243),
                                                                                      ('LNK', 'Lincoln Airport', 'Lincoln', 'Estados Unidos', true, 40.8510, -96.7592),
                                                                                      ('MBS', 'MBS International Airport', 'Saginaw', 'Estados Unidos', true, 43.5329, -84.0796),
                                                                                      ('MCI', 'Kansas City International Airport', 'Kansas City', 'Estados Unidos', true, 39.2976, -94.7139),
                                                                                      ('MDW', 'Chicago Midway International Airport', 'Chicago', 'Estados Unidos', true, 41.7868, -87.7522),
                                                                                      ('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'Estados Unidos', true, 42.9472, -87.8966),
                                                                                      ('MQT', 'Sawyer International Airport', 'Marquette', 'Estados Unidos', true, 46.3536, -87.3953),
                                                                                      ('MSN', 'Dane County Regional Airport', 'Madison', 'Estados Unidos', true, 43.1399, -89.3375),
                                                                                      ('MSP', 'Minneapolis-St Paul International Airport', 'Minneapolis', 'Estados Unidos', true, 44.8848, -93.2223),
                                                                                      ('OMA', 'Eppley Airfield', 'Omaha', 'Estados Unidos', true, 41.3025, -95.8942),
                                                                                      ('ORD', 'O''Hare International Airport', 'Chicago', 'Estados Unidos', true, 41.9742, -87.9073),
                                                                                      ('RAP', 'Rapid City Regional Airport', 'Rapid City', 'Estados Unidos', true, 44.0453, -103.0574),
                                                                                      ('RST', 'Rochester International Airport', 'Rochester', 'Estados Unidos', true, 43.9088, -92.4979),
                                                                                      ('SBN', 'South Bend International Airport', 'South Bend', 'Estados Unidos', true, 41.7087, -86.3173),
                                                                                      ('SDF', 'Louisville Muhammad Ali International Airport', 'Louisville', 'Estados Unidos', true, 38.1744, -85.7360),
                                                                                      ('SGF', 'Springfield-Branson National Airport', 'Springfield', 'Estados Unidos', true, 37.2457, -93.3886),
                                                                                      ('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'Estados Unidos', true, 38.7472, -90.3614),
                                                                                      ('TUL', 'Tulsa International Airport', 'Tulsa', 'Estados Unidos', true, 36.1984, -95.8882),
                                                                                      ('TVC', 'Cherry Capital Airport', 'Traverse City', 'Estados Unidos', true, 44.7414, -85.5822),
                                                                                      ('XNA', 'Northwest Arkansas National Airport', 'Fayetteville', 'Estados Unidos', true, 36.2819, -94.3068);

-- ============================================
-- Insertar AEROPUERTOS - Región Oeste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'Estados Unidos', true, 35.0402, -106.6091),
                                                                                      ('AMA', 'Rick Husband Amarillo International Airport', 'Amarillo', 'Estados Unidos', true, 35.2194, -101.6658),
                                                                                      ('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'Estados Unidos', true, 61.1759, -149.9901),
                                                                                      ('BFL', 'Meadows Field', 'Bakersfield', 'Estados Unidos', true, 35.4336, -119.0567),
                                                                                      ('BOI', 'Boise Airport', 'Boise', 'Estados Unidos', true, 43.5644, -116.2227),
                                                                                      ('BUR', 'Hollywood Burbank Airport', 'Burbank', 'Estados Unidos', true, 34.2007, -118.3590),
                                                                                      ('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'Estados Unidos', true, 45.7769, -111.1530),
                                                                                      ('COS', 'Colorado Springs Airport', 'Colorado Springs', 'Estados Unidos', true, 38.8058, -104.7003),
                                                                                      ('DAL', 'Dallas Love Field', 'Dallas', 'Estados Unidos', true, 32.8471, -96.8518),
                                                                                      ('DEN', 'Denver International Airport', 'Denver', 'Estados Unidos', true, 39.8561, -104.6737),
                                                                                      ('DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'Estados Unidos', true, 32.8998, -97.0403),
                                                                                      ('DRO', 'Durango-La Plata County Airport', 'Durango', 'Estados Unidos', true, 37.1515, -107.7538),
                                                                                      ('EGE', 'Eagle County Regional Airport', 'Vail', 'Estados Unidos', true, 39.6396, -106.9121),
                                                                                      ('ELP', 'El Paso International Airport', 'El Paso', 'Estados Unidos', true, 31.8073, -106.3776),
                                                                                      ('EUG', 'Eugene Airport', 'Eugene', 'Estados Unidos', true, 44.1233, -123.2187),
                                                                                      ('FAI', 'Fairbanks International Airport', 'Fairbanks', 'Estados Unidos', true, 64.8148, -147.8563),
                                                                                      ('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'Estados Unidos', true, 36.7762, -119.7181),
                                                                                      ('FCA', 'Glacier Park International Airport', 'Kalispell', 'Estados Unidos', true, 48.3114, -114.2560),
                                                                                      ('GEG', 'Spokane International Airport', 'Spokane', 'Estados Unidos', true, 47.6190, -117.5352),
                                                                                      ('GJT', 'Grand Junction Regional Airport', 'Grand Junction', 'Estados Unidos', true, 39.1224, -108.5267),
                                                                                      ('GUC', 'Gunnison-Crested Butte Regional Airport', 'Gunnison', 'Estados Unidos', true, 38.5339, -106.9331),
                                                                                      ('HDN', 'Yampa Valley Airport', 'Hayden', 'Estados Unidos', true, 40.4812, -107.2176),
                                                                                      ('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'Estados Unidos', true, 21.3187, -157.9225),
                                                                                      ('HOB', 'Lea County Regional Airport', 'Hobbs', 'Estados Unidos', true, 32.6875, -103.2170),
                                                                                      ('IAH', 'George Bush Intercontinental Airport', 'Houston', 'Estados Unidos', true, 29.9902, -95.3368),
                                                                                      ('JNU', 'Juneau International Airport', 'Juneau', 'Estados Unidos', true, 58.3549, -134.5762),
                                                                                      ('JAC', 'Jackson Hole Airport', 'Jackson', 'Estados Unidos', true, 43.6073, -110.7377),
                                                                                      ('KOA', 'Ellison Onizuka Kona International Airport', 'Kailua-Kona', 'Estados Unidos', true, 19.7388, -156.0462),
                                                                                      ('KTN', 'Ketchikan International Airport', 'Ketchikan', 'Estados Unidos', true, 55.3556, -131.7137),
                                                                                      ('LAS', 'Harry Reid International Airport', 'Las Vegas', 'Estados Unidos', true, 36.0840, -115.1537),
                                                                                      ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'Estados Unidos', true, 33.9416, -118.4085),
                                                                                      ('LBB', 'Lubbock Preston Smith International Airport', 'Lubbock', 'Estados Unidos', true, 33.6636, -101.8228),
                                                                                      ('LIH', 'Lihue Airport', 'Lihue', 'Estados Unidos', true, 21.9760, -159.3390),
                                                                                      ('LRD', 'Laredo International Airport', 'Laredo', 'Estados Unidos', true, 27.5437, -99.4615),
                                                                                      ('MAF', 'Midland International Air and Space Port', 'Midland', 'Estados Unidos', true, 31.9425, -102.2019),
                                                                                      ('MFE', 'McAllen Miller International Airport', 'McAllen', 'Estados Unidos', true, 26.1758, -98.2386),
                                                                                      ('MRY', 'Monterey Regional Airport', 'Monterey', 'Estados Unidos', true, 36.5870, -121.8429),
                                                                                      ('MSO', 'Missoula International Airport', 'Missoula', 'Estados Unidos', true, 46.9163, -114.0906),
                                                                                      ('MTJ', 'Montrose Regional Airport', 'Montrose', 'Estados Unidos', true, 38.5089, -107.8938),
                                                                                      ('OAK', 'Oakland International Airport', 'Oakland', 'Estados Unidos', true, 37.7214, -122.2208),
                                                                                      ('OGG', 'Kahului Airport', 'Kahului', 'Estados Unidos', true, 20.8986, -156.4305),
                                                                                      ('OKC', 'Will Rogers World Airport', 'Oklahoma City', 'Estados Unidos', true, 35.3931, -97.6007),
                                                                                      ('ONT', 'Ontario International Airport', 'Ontario', 'Estados Unidos', true, 34.0560, -117.6012),
                                                                                      ('PAE', 'Paine Field', 'Everett', 'Estados Unidos', true, 47.9073, -122.2814),
                                                                                      ('PDX', 'Portland International Airport', 'Portland', 'Estados Unidos', true, 45.5898, -122.5951),
                                                                                      ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'Estados Unidos', true, 33.4343, -112.0116),
                                                                                      ('PSC', 'Tri-Cities Airport', 'Pasco', 'Estados Unidos', true, 46.2647, -119.1190),
                                                                                      ('PSP', 'Palm Springs International Airport', 'Palm Springs', 'Estados Unidos', true, 33.8297, -116.5067),
                                                                                      ('RDM', 'Roberts Field', 'Redmond', 'Estados Unidos', true, 44.2541, -121.1500),
                                                                                      ('RNO', 'Reno-Tahoe International Airport', 'Reno', 'Estados Unidos', true, 39.4996, -119.7681),
                                                                                      ('SAF', 'Santa Fe Municipal Airport', 'Santa Fe', 'Estados Unidos', true, 35.6171, -106.0894),
                                                                                      ('SAN', 'San Diego International Airport', 'San Diego', 'Estados Unidos', true, 32.7338, -117.1933),
                                                                                      ('SAT', 'San Antonio International Airport', 'San Antonio', 'Estados Unidos', true, 29.5312, -98.4683),
                                                                                      ('SBA', 'Santa Barbara Municipal Airport', 'Santa Barbara', 'Estados Unidos', true, 34.4261, -119.8407),
                                                                                      ('SBP', 'San Luis Obispo County Regional Airport', 'San Luis Obispo', 'Estados Unidos', true, 35.2371, -120.6425),
                                                                                      ('SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'Estados Unidos', true, 47.4502, -122.3088),
                                                                                      ('SFO', 'San Francisco International Airport', 'San Francisco', 'Estados Unidos', true, 37.6188, -122.3758),
                                                                                      ('SIT', 'Sitka Rocky Gutierrez Airport', 'Sitka', 'Estados Unidos', true, 57.0471, -135.3616),
                                                                                      ('SJC', 'Norman Y. Mineta San Jose International Airport', 'San Jose', 'Estados Unidos', true, 37.3619, -121.9290),
                                                                                      ('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'Estados Unidos', true, 40.7899, -111.9791),
                                                                                      ('SMF', 'Sacramento International Airport', 'Sacramento', 'Estados Unidos', true, 38.6954, -121.5908),
                                                                                      ('SNA', 'John Wayne Airport', 'Santa Ana', 'Estados Unidos', true, 33.6757, -117.8674),
                                                                                      ('STS', 'Charles M. Schulz-Sonoma County Airport', 'Santa Rosa', 'Estados Unidos', true, 38.5088, -122.8129),
                                                                                      ('TUS', 'Tucson International Airport', 'Tucson', 'Estados Unidos', true, 32.1145, -110.9392),
                                                                                      ('COD', 'Yellowstone Regional Airport', 'Cody', 'Estados Unidos', true, 44.5201, -109.0238),
                                                                                      ('CPR', 'Casper-Natrona County International Airport', 'Casper', 'Estados Unidos', true, 42.9080, -106.4644);

-- ============================================
-- Insertar AEROPUERTOS - Alaska adicionales
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ADK', 'Adak Airport', 'Adak Island', 'Estados Unidos', true, 51.8779, -176.6460),
                                                                                      ('ADQ', 'Kodiak Airport', 'Kodiak', 'Estados Unidos', true, 57.7499, -152.4938),
                                                                                      ('AKN', 'King Salmon Airport', 'King Salmon', 'Estados Unidos', true, 58.6768, -156.6492),
                                                                                      ('BET', 'Bethel Airport', 'Bethel', 'Estados Unidos', true, 60.7797, -161.8380),
                                                                                      ('BRW', 'Wiley Post-Will Rogers Memorial Airport', 'Utqiaġvik', 'Estados Unidos', true, 71.2854, -156.7660),
                                                                                      ('CDV', 'Merle K. (Mudhole) Smith Airport', 'Cordova', 'Estados Unidos', true, 60.4918, -145.4776),
                                                                                      ('OME', 'Nome Airport', 'Nome', 'Estados Unidos', true, 64.5122, -165.4452),
                                                                                      ('OTZ', 'Ralph Wien Memorial Airport', 'Kotzebue', 'Estados Unidos', true, 66.8847, -162.5985),
                                                                                      ('PSG', 'Petersburg James A. Johnson Airport', 'Petersburg', 'Estados Unidos', true, 56.8016, -132.9452),
                                                                                      ('WRG', 'Wrangell Airport', 'Wrangell', 'Estados Unidos', true, 56.4843, -132.3698),
                                                                                      ('YAK', 'Yakutat Airport', 'Yakutat', 'Estados Unidos', true, 59.5033, -139.6602);

-- ============================================
-- Insertar AEROPUERTOS - Adicionales
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo, latitud, longitud) VALUES
                                                                                      ('ABY', 'Southwest Georgia Regional Airport', 'Albany', 'Estados Unidos', true, 31.5355, -84.1945),
                                                                                      ('AEX', 'Alexandria International Airport', 'Alexandria', 'Estados Unidos', true, 31.3274, -92.5486),
                                                                                      ('AGS', 'Augusta Regional Airport', 'Augusta', 'Estados Unidos', true, 33.3699, -81.9645),
                                                                                      ('BQK', 'Brunswick Golden Isles Airport', 'Brunswick', 'Estados Unidos', true, 31.2588, -81.4663),
                                                                                      ('DIK', 'Dickinson Theodore Roosevelt Regional Airport', 'Dickinson', 'Estados Unidos', true, 46.7975, -102.8021),
                                                                                      ('LSE', 'La Crosse Regional Airport', 'La Crosse', 'Estados Unidos', true, 43.8794, -91.2565),
                                                                                      ('MOT', 'Minot International Airport', 'Minot', 'Estados Unidos', true, 48.2594, -101.2776),
                                                                                      ('SCC', 'Deadhorse Airport', 'Deadhorse', 'Estados Unidos', true, 70.1947, -148.4652),
                                                                                      ('SCE', 'University Park Airport', 'State College', 'Estados Unidos', true, 40.8512, -77.8463);