-- ============================================
-- Insertar AEROLÍNEAS
-- ============================================
INSERT INTO aerolineas (codigo, nombre, pais_origen, activa) VALUES
('9E', 'Endeavor Air', 'Estados Unidos', true),
('AA', 'American Airlines', 'Estados Unidos', true),
('AS', 'Alaska Airlines', 'Estados Unidos', true),
('B6', 'JetBlue Airways', 'Estados Unidos', true),
('C5', 'CommutAir', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Región Noreste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ABE', 'Lehigh Valley International Airport', 'Allentown', 'Estados Unidos', true),
('ALB', 'Albany International Airport', 'Albany', 'Estados Unidos', true),
('AVP', 'Wilkes-Barre/Scranton International Airport', 'Scranton', 'Estados Unidos', true),
('BDL', 'Bradley International Airport', 'Hartford', 'Estados Unidos', true),
('BGM', 'Greater Binghamton Airport', 'Binghamton', 'Estados Unidos', true),
('BGR', 'Bangor International Airport', 'Bangor', 'Estados Unidos', true),
('BOS', 'Logan International Airport', 'Boston', 'Estados Unidos', true),
('BTV', 'Burlington International Airport', 'Burlington', 'Estados Unidos', true),
('BUF', 'Buffalo Niagara International Airport', 'Buffalo', 'Estados Unidos', true),
('BWI', 'Baltimore/Washington International Airport', 'Baltimore', 'Estados Unidos', true),
('DCA', 'Ronald Reagan Washington National Airport', 'Washington', 'Estados Unidos', true),
('EWR', 'Newark Liberty International Airport', 'Newark', 'Estados Unidos', true),
('HPN', 'Westchester County Airport', 'White Plains', 'Estados Unidos', true),
('IAD', 'Washington Dulles International Airport', 'Washington', 'Estados Unidos', true),
('ITH', 'Ithaca Tompkins International Airport', 'Ithaca', 'Estados Unidos', true),
('JFK', 'John F. Kennedy International Airport', 'New York', 'Estados Unidos', true),
('LGA', 'LaGuardia Airport', 'New York', 'Estados Unidos', true),
('MDT', 'Harrisburg International Airport', 'Harrisburg', 'Estados Unidos', true),
('MHT', 'Manchester-Boston Regional Airport', 'Manchester', 'Estados Unidos', true),
('ORH', 'Worcester Regional Airport', 'Worcester', 'Estados Unidos', true),
('PHL', 'Philadelphia International Airport', 'Philadelphia', 'Estados Unidos', true),
('PIT', 'Pittsburgh International Airport', 'Pittsburgh', 'Estados Unidos', true),
('PVD', 'Rhode Island T.F. Green International Airport', 'Providence', 'Estados Unidos', true),
('PWM', 'Portland International Jetport', 'Portland', 'Estados Unidos', true),
('ROC', 'Greater Rochester International Airport', 'Rochester', 'Estados Unidos', true),
('SYR', 'Syracuse Hancock International Airport', 'Syracuse', 'Estados Unidos', true),
('ACK', 'Nantucket Memorial Airport', 'Nantucket', 'Estados Unidos', true),
('MVY', 'Martha''s Vineyard Airport', 'Martha''s Vineyard', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Región Sureste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'Estados Unidos', true),
('AVL', 'Asheville Regional Airport', 'Asheville', 'Estados Unidos', true),
('BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham', 'Estados Unidos', true),
('BNA', 'Nashville International Airport', 'Nashville', 'Estados Unidos', true),
('BTR', 'Baton Rouge Metropolitan Airport', 'Baton Rouge', 'Estados Unidos', true),
('CAE', 'Columbia Metropolitan Airport', 'Columbia', 'Estados Unidos', true),
('CHA', 'Chattanooga Metropolitan Airport', 'Chattanooga', 'Estados Unidos', true),
('CHO', 'Charlottesville-Albemarle Airport', 'Charlottesville', 'Estados Unidos', true),
('CHS', 'Charleston International Airport', 'Charleston', 'Estados Unidos', true),
('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'Estados Unidos', true),
('CSG', 'Columbus Airport', 'Columbus', 'Estados Unidos', true),
('DAB', 'Daytona Beach International Airport', 'Daytona Beach', 'Estados Unidos', true),
('DHN', 'Dothan Regional Airport', 'Dothan', 'Estados Unidos', true),
('EYW', 'Key West International Airport', 'Key West', 'Estados Unidos', true),
('FAY', 'Fayetteville Regional Airport', 'Fayetteville', 'Estados Unidos', true),
('FLL', 'Fort Lauderdale-Hollywood International Airport', 'Fort Lauderdale', 'Estados Unidos', true),
('GNV', 'Gainesville Regional Airport', 'Gainesville', 'Estados Unidos', true),
('GPT', 'Gulfport-Biloxi International Airport', 'Gulfport', 'Estados Unidos', true),
('GSO', 'Piedmont Triad International Airport', 'Greensboro', 'Estados Unidos', true),
('GSP', 'Greenville-Spartanburg International Airport', 'Greenville', 'Estados Unidos', true),
('GTR', 'Golden Triangle Regional Airport', 'Columbus', 'Estados Unidos', true),
('HSV', 'Huntsville International Airport', 'Huntsville', 'Estados Unidos', true),
('ILM', 'Wilmington International Airport', 'Wilmington', 'Estados Unidos', true),
('JAN', 'Jackson-Medgar Wiley Evers International Airport', 'Jackson', 'Estados Unidos', true),
('JAX', 'Jacksonville International Airport', 'Jacksonville', 'Estados Unidos', true),
('LCH', 'Lake Charles Regional Airport', 'Lake Charles', 'Estados Unidos', true),
('LEX', 'Blue Grass Airport', 'Lexington', 'Estados Unidos', true),
('LFT', 'Lafayette Regional Airport', 'Lafayette', 'Estados Unidos', true),
('MCO', 'Orlando International Airport', 'Orlando', 'Estados Unidos', true),
('MEM', 'Memphis International Airport', 'Memphis', 'Estados Unidos', true),
('MGM', 'Montgomery Regional Airport', 'Montgomery', 'Estados Unidos', true),
('MIA', 'Miami International Airport', 'Miami', 'Estados Unidos', true),
('MLI', 'Quad City International Airport', 'Moline', 'Estados Unidos', true),
('MLU', 'Monroe Regional Airport', 'Monroe', 'Estados Unidos', true),
('MOB', 'Mobile Regional Airport', 'Mobile', 'Estados Unidos', true),
('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'Estados Unidos', true),
('MYR', 'Myrtle Beach International Airport', 'Myrtle Beach', 'Estados Unidos', true),
('OAJ', 'Albert J. Ellis Airport', 'Jacksonville', 'Estados Unidos', true),
('ORF', 'Norfolk International Airport', 'Norfolk', 'Estados Unidos', true),
('PBI', 'Palm Beach International Airport', 'West Palm Beach', 'Estados Unidos', true),
('PNS', 'Pensacola International Airport', 'Pensacola', 'Estados Unidos', true),
('RDU', 'Raleigh-Durham International Airport', 'Raleigh', 'Estados Unidos', true),
('RIC', 'Richmond International Airport', 'Richmond', 'Estados Unidos', true),
('ROA', 'Roanoke-Blacksburg Regional Airport', 'Roanoke', 'Estados Unidos', true),
('RSW', 'Southwest Florida International Airport', 'Fort Myers', 'Estados Unidos', true),
('SAV', 'Savannah/Hilton Head International Airport', 'Savannah', 'Estados Unidos', true),
('SHV', 'Shreveport Regional Airport', 'Shreveport', 'Estados Unidos', true),
('SRQ', 'Sarasota-Bradenton International Airport', 'Sarasota', 'Estados Unidos', true),
('TLH', 'Tallahassee International Airport', 'Tallahassee', 'Estados Unidos', true),
('TPA', 'Tampa International Airport', 'Tampa', 'Estados Unidos', true),
('TRI', 'Tri-Cities Airport', 'Bristol', 'Estados Unidos', true),
('TYS', 'McGhee Tyson Airport', 'Knoxville', 'Estados Unidos', true),
('VLD', 'Valdosta Regional Airport', 'Valdosta', 'Estados Unidos', true),
('VPS', 'Destin-Fort Walton Beach Airport', 'Valparaiso', 'Estados Unidos', true),
('BRO', 'Brownsville/South Padre Island International Airport', 'Brownsville', 'Estados Unidos', true),
('CRP', 'Corpus Christi International Airport', 'Corpus Christi', 'Estados Unidos', true),
('HRL', 'Valley International Airport', 'Harlingen', 'Estados Unidos', true),
('BQN', 'Rafael Hernández Airport', 'Aguadilla', 'Puerto Rico', true),
('PSE', 'Mercedita Airport', 'Ponce', 'Puerto Rico', true),
('SJU', 'Luis Muñoz Marín International Airport', 'San Juan', 'Puerto Rico', true),
('STT', 'Cyril E. King Airport', 'Charlotte Amalie', 'Islas Vírgenes de EE.UU.', true),
('STX', 'Henry E. Rohlsen Airport', 'Christiansted', 'Islas Vírgenes de EE.UU.', true),
('ECP', 'Northwest Florida Beaches International Airport', 'Panama City', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Región Medio Oeste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ATW', 'Appleton International Airport', 'Appleton', 'Estados Unidos', true),
('AZO', 'Kalamazoo/Battle Creek International Airport', 'Kalamazoo', 'Estados Unidos', true),
('BMI', 'Central Illinois Regional Airport', 'Bloomington', 'Estados Unidos', true),
('CID', 'The Eastern Iowa Airport', 'Cedar Rapids', 'Estados Unidos', true),
('CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'Estados Unidos', true),
('CMH', 'John Glenn Columbus International Airport', 'Columbus', 'Estados Unidos', true),
('CRW', 'Yeager Airport', 'Charleston', 'Estados Unidos', true),
('CVG', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati', 'Estados Unidos', true),
('CWA', 'Central Wisconsin Airport', 'Wausau', 'Estados Unidos', true),
('DAY', 'James M. Cox Dayton International Airport', 'Dayton', 'Estados Unidos', true),
('DLH', 'Duluth International Airport', 'Duluth', 'Estados Unidos', true),
('DSM', 'Des Moines International Airport', 'Des Moines', 'Estados Unidos', true),
('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'Estados Unidos', true),
('EVV', 'Evansville Regional Airport', 'Evansville', 'Estados Unidos', true),
('FAR', 'Hector International Airport', 'Fargo', 'Estados Unidos', true),
('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'Estados Unidos', true),
('GFK', 'Grand Forks International Airport', 'Grand Forks', 'Estados Unidos', true),
('GRB', 'Green Bay-Austin Straubel International Airport', 'Green Bay', 'Estados Unidos', true),
('GRR', 'Gerald R. Ford International Airport', 'Grand Rapids', 'Estados Unidos', true),
('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'Estados Unidos', true),
('IND', 'Indianapolis International Airport', 'Indianapolis', 'Estados Unidos', true),
('LAN', 'Capital Region International Airport', 'Lansing', 'Estados Unidos', true),
('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'Estados Unidos', true),
('LNK', 'Lincoln Airport', 'Lincoln', 'Estados Unidos', true),
('MBS', 'MBS International Airport', 'Saginaw', 'Estados Unidos', true),
('MCI', 'Kansas City International Airport', 'Kansas City', 'Estados Unidos', true),
('MDW', 'Chicago Midway International Airport', 'Chicago', 'Estados Unidos', true),
('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'Estados Unidos', true),
('MQT', 'Sawyer International Airport', 'Marquette', 'Estados Unidos', true),
('MSN', 'Dane County Regional Airport', 'Madison', 'Estados Unidos', true),
('MSP', 'Minneapolis-St Paul International Airport', 'Minneapolis', 'Estados Unidos', true),
('OMA', 'Eppley Airfield', 'Omaha', 'Estados Unidos', true),
('ORD', 'O''Hare International Airport', 'Chicago', 'Estados Unidos', true),
('RAP', 'Rapid City Regional Airport', 'Rapid City', 'Estados Unidos', true),
('RST', 'Rochester International Airport', 'Rochester', 'Estados Unidos', true),
('SBN', 'South Bend International Airport', 'South Bend', 'Estados Unidos', true),
('SDF', 'Louisville Muhammad Ali International Airport', 'Louisville', 'Estados Unidos', true),
('SGF', 'Springfield-Branson National Airport', 'Springfield', 'Estados Unidos', true),
('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'Estados Unidos', true),
('TUL', 'Tulsa International Airport', 'Tulsa', 'Estados Unidos', true),
('TVC', 'Cherry Capital Airport', 'Traverse City', 'Estados Unidos', true),
('XNA', 'Northwest Arkansas National Airport', 'Fayetteville', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Región Oeste
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'Estados Unidos', true),
('AMA', 'Rick Husband Amarillo International Airport', 'Amarillo', 'Estados Unidos', true),
('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'Estados Unidos', true),
('BFL', 'Meadows Field', 'Bakersfield', 'Estados Unidos', true),
('BOI', 'Boise Airport', 'Boise', 'Estados Unidos', true),
('BUR', 'Hollywood Burbank Airport', 'Burbank', 'Estados Unidos', true),
('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'Estados Unidos', true),
('COS', 'Colorado Springs Airport', 'Colorado Springs', 'Estados Unidos', true),
('DAL', 'Dallas Love Field', 'Dallas', 'Estados Unidos', true),
('DEN', 'Denver International Airport', 'Denver', 'Estados Unidos', true),
('DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'Estados Unidos', true),
('DRO', 'Durango-La Plata County Airport', 'Durango', 'Estados Unidos', true),
('EGE', 'Eagle County Regional Airport', 'Vail', 'Estados Unidos', true),
('ELP', 'El Paso International Airport', 'El Paso', 'Estados Unidos', true),
('EUG', 'Eugene Airport', 'Eugene', 'Estados Unidos', true),
('FAI', 'Fairbanks International Airport', 'Fairbanks', 'Estados Unidos', true),
('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'Estados Unidos', true),
('FCA', 'Glacier Park International Airport', 'Kalispell', 'Estados Unidos', true),
('GEG', 'Spokane International Airport', 'Spokane', 'Estados Unidos', true),
('GJT', 'Grand Junction Regional Airport', 'Grand Junction', 'Estados Unidos', true),
('GUC', 'Gunnison-Crested Butte Regional Airport', 'Gunnison', 'Estados Unidos', true),
('HDN', 'Yampa Valley Airport', 'Hayden', 'Estados Unidos', true),
('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'Estados Unidos', true),
('HOB', 'Lea County Regional Airport', 'Hobbs', 'Estados Unidos', true),
('IAH', 'George Bush Intercontinental Airport', 'Houston', 'Estados Unidos', true),
('JNU', 'Juneau International Airport', 'Juneau', 'Estados Unidos', true),
('JAC', 'Jackson Hole Airport', 'Jackson', 'Estados Unidos', true),
('KOA', 'Ellison Onizuka Kona International Airport', 'Kailua-Kona', 'Estados Unidos', true),
('KTN', 'Ketchikan International Airport', 'Ketchikan', 'Estados Unidos', true),
('LAS', 'Harry Reid International Airport', 'Las Vegas', 'Estados Unidos', true),
('LAX', 'Los Angeles International Airport', 'Los Angeles', 'Estados Unidos', true),
('LBB', 'Lubbock Preston Smith International Airport', 'Lubbock', 'Estados Unidos', true),
('LIH', 'Lihue Airport', 'Lihue', 'Estados Unidos', true),
('LRD', 'Laredo International Airport', 'Laredo', 'Estados Unidos', true),
('MAF', 'Midland International Air and Space Port', 'Midland', 'Estados Unidos', true),
('MFE', 'McAllen Miller International Airport', 'McAllen', 'Estados Unidos', true),
('MRY', 'Monterey Regional Airport', 'Monterey', 'Estados Unidos', true),
('MSO', 'Missoula International Airport', 'Missoula', 'Estados Unidos', true),
('MTJ', 'Montrose Regional Airport', 'Montrose', 'Estados Unidos', true),
('OAK', 'Oakland International Airport', 'Oakland', 'Estados Unidos', true),
('OGG', 'Kahului Airport', 'Kahului', 'Estados Unidos', true),
('OKC', 'Will Rogers World Airport', 'Oklahoma City', 'Estados Unidos', true),
('ONT', 'Ontario International Airport', 'Ontario', 'Estados Unidos', true),
('PAE', 'Paine Field', 'Everett', 'Estados Unidos', true),
('PDX', 'Portland International Airport', 'Portland', 'Estados Unidos', true),
('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'Estados Unidos', true),
('PSC', 'Tri-Cities Airport', 'Pasco', 'Estados Unidos', true),
('PSP', 'Palm Springs International Airport', 'Palm Springs', 'Estados Unidos', true),
('RDM', 'Roberts Field', 'Redmond', 'Estados Unidos', true),
('RNO', 'Reno-Tahoe International Airport', 'Reno', 'Estados Unidos', true),
('SAF', 'Santa Fe Municipal Airport', 'Santa Fe', 'Estados Unidos', true),
('SAN', 'San Diego International Airport', 'San Diego', 'Estados Unidos', true),
('SAT', 'San Antonio International Airport', 'San Antonio', 'Estados Unidos', true),
('SBA', 'Santa Barbara Municipal Airport', 'Santa Barbara', 'Estados Unidos', true),
('SBP', 'San Luis Obispo County Regional Airport', 'San Luis Obispo', 'Estados Unidos', true),
('SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'Estados Unidos', true),
('SFO', 'San Francisco International Airport', 'San Francisco', 'Estados Unidos', true),
('SIT', 'Sitka Rocky Gutierrez Airport', 'Sitka', 'Estados Unidos', true),
('SJC', 'Norman Y. Mineta San Jose International Airport', 'San Jose', 'Estados Unidos', true),
('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'Estados Unidos', true),
('SMF', 'Sacramento International Airport', 'Sacramento', 'Estados Unidos', true),
('SNA', 'John Wayne Airport', 'Santa Ana', 'Estados Unidos', true),
('STS', 'Charles M. Schulz-Sonoma County Airport', 'Santa Rosa', 'Estados Unidos', true),
('TUS', 'Tucson International Airport', 'Tucson', 'Estados Unidos', true),
('COD', 'Yellowstone Regional Airport', 'Cody', 'Estados Unidos', true),
('CPR', 'Casper-Natrona County International Airport', 'Casper', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Alaska adicionales
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ADK', 'Adak Airport', 'Adak Island', 'Estados Unidos', true),
('ADQ', 'Kodiak Airport', 'Kodiak', 'Estados Unidos', true),
('AKN', 'King Salmon Airport', 'King Salmon', 'Estados Unidos', true),
('BET', 'Bethel Airport', 'Bethel', 'Estados Unidos', true),
('BRW', 'Wiley Post-Will Rogers Memorial Airport', 'Utqiaġvik', 'Estados Unidos', true),
('CDV', 'Merle K. (Mudhole) Smith Airport', 'Cordova', 'Estados Unidos', true),
('OME', 'Nome Airport', 'Nome', 'Estados Unidos', true),
('OTZ', 'Ralph Wien Memorial Airport', 'Kotzebue', 'Estados Unidos', true),
('PSG', 'Petersburg James A. Johnson Airport', 'Petersburg', 'Estados Unidos', true),
('WRG', 'Wrangell Airport', 'Wrangell', 'Estados Unidos', true),
('YAK', 'Yakutat Airport', 'Yakutat', 'Estados Unidos', true);

-- ============================================
-- Insertar AEROPUERTOS - Adicionales
-- ============================================
INSERT INTO aeropuertos (codigo, nombre, ciudad, pais, activo) VALUES
('ABY', 'Southwest Georgia Regional Airport', 'Albany', 'Estados Unidos', true),
('AEX', 'Alexandria International Airport', 'Alexandria', 'Estados Unidos', true),
('AGS', 'Augusta Regional Airport', 'Augusta', 'Estados Unidos', true),
('BQK', 'Brunswick Golden Isles Airport', 'Brunswick', 'Estados Unidos', true),
('DIK', 'Dickinson Theodore Roosevelt Regional Airport', 'Dickinson', 'Estados Unidos', true),
('LSE', 'La Crosse Regional Airport', 'La Crosse', 'Estados Unidos', true),
('MOT', 'Minot International Airport', 'Minot', 'Estados Unidos', true),
('SCC', 'Deadhorse Airport', 'Deadhorse', 'Estados Unidos', true),
('SCE', 'University Park Airport', 'State College', 'Estados Unidos', true);