--Eliminar columnas que no se usan
ALTER TABLE aeropuertos DROP COLUMN IF EXISTS pais;
ALTER TABLE aeropuertos DROP COLUMN IF EXISTS fecha_creacion;

--Agregar nuevas columnas booleanas
ALTER TABLE aeropuertos ADD COLUMN es_origen BOOLEAN DEFAULT FALSE;
ALTER TABLE aeropuertos ADD COLUMN es_destino BOOLEAN DEFAULT FALSE;

--Crear índices
CREATE INDEX idx_aeropuertos_es_origen ON aeropuertos(es_origen) WHERE es_origen = TRUE;
CREATE INDEX idx_aeropuertos_es_destino ON aeropuertos(es_destino) WHERE es_destino = TRUE;

--Limpiar datos existentes
DELETE FROM aeropuertos;
--Reiniciar el secuenciador para que los IDs empiecen desde 1
ALTER SEQUENCE aeropuertos_id_seq RESTART WITH 1;

--INSERTAR AEROPUERTOS DE ORIGEN (61 aeropuertos)
INSERT INTO aeropuertos (codigo, ciudad, nombre, es_origen, es_destino) VALUES
('ABQ', 'Albuquerque', 'Albuquerque International Sunport Airport', TRUE, FALSE),
('ANC', 'Anchorage', 'Ted Stevens Anchorage International Airport', TRUE, FALSE),
('ATL', 'Atlanta', 'Hartsfield-Jackson Atlanta International Airport', TRUE, FALSE),
('AUS', 'Austin', 'Austin-Bergstrom International Airport', TRUE, FALSE),
('BDL', 'Hartford', 'Bradley International Airport', TRUE, FALSE),
('BNA', 'Nashville', 'Nashville International Airport', TRUE, FALSE),
('BOI', 'Boise', 'Boise Air Terminal Airport', TRUE, FALSE),
('BOS', 'Boston', 'Boston Logan International Airport', TRUE, FALSE),
('BUR', 'Burbank', 'Bob Hope Airport', TRUE, FALSE),
('BWI', 'Baltimore-Washington', 'Baltimore/Washington International Thurgood Marshall Airport', TRUE, FALSE),
('CHS', 'Charleston', 'Charleston International Airport', TRUE, FALSE),
('CLE', 'Cleveland', 'Cleveland Hopkins International Airport', TRUE, FALSE),
('CLT', 'Charlotte', 'Charlotte Douglas International Airport', TRUE, FALSE),
('CMH', 'Columbus', 'John Glenn Columbus International Airport', TRUE, FALSE),
('CVG', 'Cincinnati', 'Cincinnati/Northern Kentucky International Airport', TRUE, FALSE),
('DCA', 'Washington D.C.', 'Ronald Reagan Washington National Airport', TRUE, FALSE),
('DEN', 'Denver', 'Denver International Airport', TRUE, FALSE),
('DFW', 'Dallas-Fort Worth', 'Dallas/Fort Worth International Airport', TRUE, FALSE),
('DTW', 'Detroit', 'Detroit Metropolitan Wayne County Airport', TRUE, FALSE),
('EWR', 'Newark', 'Newark Liberty International Airport', TRUE, FALSE),
('FLL', 'Fort Lauderdale', 'Fort Lauderdale-Hollywood International Airport', TRUE, FALSE),
('HOU', 'Houston', 'Houston Hobby Airport', TRUE, FALSE),
('IAD', 'Washington D.C.', 'Washington Dulles International Airport', TRUE, FALSE),
('IAH', 'Houston', 'Houston William P. Hobby International Airport', TRUE, FALSE),
('IND', 'Indianapolis', 'Indianapolis International Airport', TRUE, FALSE),
('JAX', 'Jacksonville', 'Jacksonville International Airport', TRUE, FALSE),
('JFK', 'New York', 'John F. Kennedy International Airport', TRUE, FALSE),
('LAS', 'Las Vegas', 'Harry Reid International Airport', TRUE, FALSE),
('LAX', 'Los Angeles', 'Los Angeles International Airport', TRUE, FALSE),
('LGA', 'New York', 'LaGuardia Airport', TRUE, FALSE),
('MCI', 'Kansas City', 'Kansas City International Airport', TRUE, FALSE),
('MCO', 'Orlando', 'Orlando International Airport', TRUE, FALSE),
('MDW', 'Chicago', 'Chicago Midway International Airport', TRUE, FALSE),
('MEM', 'Memphis', 'Memphis International Airport', TRUE, FALSE),
('MIA', 'Miami', 'Miami International Airport', TRUE, FALSE),
('MKE', 'Milwaukee', 'Milwaukee Mitchell International Airport', TRUE, FALSE),
('MSP', 'Minneapolis-Saint Paul', 'Minneapolis-Saint Paul International Airport', TRUE, FALSE),
('MSY', 'New Orleans', 'Louis Armstrong New Orleans International Airport', TRUE, FALSE),
('OAK', 'Oakland', 'Oakland International Airport', TRUE, FALSE),
('OMA', 'Omaha', 'Eppley Airfield', TRUE, FALSE),
('ONT', 'Ontario', 'Ontario International Airport', TRUE, FALSE),
('ORD', 'Chicago', 'Chicago O''Hare International Airport', TRUE, FALSE),
('PBI', 'West Palm Beach', 'Palm Beach International Airport', TRUE, FALSE),
('PDX', 'Portland', 'Portland International Airport', TRUE, FALSE),
('PHL', 'Philadelphia', 'Philadelphia International Airport', TRUE, FALSE),
('PHX', 'Phoenix', 'Phoenix Sky Harbor International Airport', TRUE, FALSE),
('PIT', 'Pittsburgh', 'Pittsburgh International Airport', TRUE, FALSE),
('RDU', 'Raleigh-Durham', 'Raleigh-Durham International Airport', TRUE, FALSE),
('RNO', 'Reno', 'Reno/Tahoe International Airport', TRUE, FALSE),
('RSW', 'Fort Myers', 'Southwest Florida International Airport', TRUE, FALSE),
('SAN', 'San Diego', 'San Diego International Airport', TRUE, FALSE),
('SAT', 'San Antonio', 'San Antonio International Airport', TRUE, FALSE),
('SEA', 'Seattle', 'Seattle-Tacoma International Airport', TRUE, FALSE),
('SFO', 'San Francisco', 'San Francisco International Airport', TRUE, FALSE),
('SJC', 'San Jose', 'San Jose International Airport', TRUE, FALSE),
('SJU', 'San Juan', 'Luis Muñoz Marín International Airport', TRUE, FALSE),
('SLC', 'Salt Lake City', 'Salt Lake City International Airport', TRUE, FALSE),
('SMF', 'Sacramento', 'Sacramento International Airport', TRUE, FALSE),
('SNA', 'Orange County', 'John Wayne Airport-Orange County', TRUE, FALSE),
('STL', 'St. Louis', 'St. Louis Lambert International Airport', TRUE, FALSE),
('TPA', 'Tampa', 'Tampa International Airport', TRUE, FALSE);

--INSERTAR AEROPUERTOS DE DESTINO (197 aeropuertos)
INSERT INTO aeropuertos (codigo, ciudad, nombre, es_origen, es_destino) VALUES
('ABE', 'Allentown', 'Lehigh Valley International Airport', FALSE, TRUE),
('ABI', 'Abilene', 'Abilene Regional Airport', FALSE, TRUE),
('ACK', 'Nantucket', 'Nantucket Memorial Airport', FALSE, TRUE),
('ACV', 'Arcata', 'Arcata-Eureka Airport', FALSE, TRUE),
('ALB', 'Albany', 'Albany International Airport', FALSE, TRUE),
('AMA', 'Amarillo', 'Amarillo International Airport', FALSE, TRUE),
('ATW', 'Appleton', 'Appleton International Airport', FALSE, TRUE),
('AVL', 'Asheville', 'Asheville Regional Airport', FALSE, TRUE),
('AVP', 'Scranton', 'Wilkes-Barre/Scranton International Airport', FALSE, TRUE),
('AZA', 'Phoenix', 'Phoenix-Mesa Gateway Airport', FALSE, TRUE),
('BFL', 'Bakersfield', 'Bakersfield Meadows Field', FALSE, TRUE),
('BGM', 'Binghamton', 'Greater Binghampton Airport', FALSE, TRUE),
('BGR', 'Bangor', 'Bangor International Airport', FALSE, TRUE),
('BHM', 'Birmingham', 'Birmingham-Shuttlesworth International Airport', FALSE, TRUE),
('BIL', 'Billings', 'Billings Logan International Airport', FALSE, TRUE),
('BIS', 'Bismarck', 'Bismarck Municipal Airport', FALSE, TRUE),
('BLI', 'Bellingham', 'Bellingham International Airport', FALSE, TRUE),
('BLV', 'Belleville', 'MidAmerica St. Louis Airport', FALSE, TRUE),
('BRO', 'Brownsville', 'Brownsville/South Padre Island International Airport', FALSE, TRUE),
('BTV', 'Burlington', 'Burlington International Airport', FALSE, TRUE),
('BUF', 'Buffalo', 'Buffalo Niagara International Airport', FALSE, TRUE),
('BZN', 'Bozeman', 'Bozeman Yellowstone International Airport', FALSE, TRUE),
('CAE', 'Columbia', 'Columbia Metropolitan Airport', FALSE, TRUE),
('CAK', 'Akron-Canton', 'Akron-Canton Regional Airport', FALSE, TRUE),
('CHA', 'Chattanooga', 'Lovell Field Airport', FALSE, TRUE),
('CHO', 'Charlottesville', 'Charlottesville-Albemarle Airport', FALSE, TRUE),
('CID', 'Cedar Rapids', 'Cedar Rapids International Airport', FALSE, TRUE),
('COD', 'Cody', 'Yellowstone Regional Airport', FALSE, TRUE),
('COS', 'Colorado Springs', 'Colorado Springs Airport', FALSE, TRUE),
('CPR', 'Casper', 'Casper-Natrona County International Airport', FALSE, TRUE),
('CRP', 'Corpus Christi', 'Corpus Christi International Airport', FALSE, TRUE),
('DAB', 'Daytona Beach', 'Daytona Beach International Airport', FALSE, TRUE),
('DAL', 'Dallas', 'Dallas Love Field', FALSE, TRUE),
('DAY', 'Dayton', 'Dayton International Airport', FALSE, TRUE),
('DLH', 'Duluth', 'Duluth International Airport', FALSE, TRUE),
('DRO', 'Durango', 'Durango-La Plata County Airport', FALSE, TRUE),
('DSM', 'Des Moines', 'Des Moines International Airport', FALSE, TRUE),
('ECP', 'Panama City', 'Panama City-Bay County International Airport', FALSE, TRUE),
('EGE', 'Eagle', 'Eagle County Regional Airport', FALSE, TRUE),
('ELP', 'El Paso', 'El Paso International Airport', FALSE, TRUE),
('EUG', 'Eugene', 'Eugene Airport', FALSE, TRUE),
('FAI', 'Fairbanks', 'Fairbanks Ted Stevens International Airport', FALSE, TRUE),
('FAR', 'Fargo', 'Hector International Airport', FALSE, TRUE),
('FAT', 'Fresno', 'Fresno Yosemite International Airport', FALSE, TRUE),
('FCA', 'Kalispell', 'Kalispell Regional Airport', FALSE, TRUE),
('FNT', 'Flint', 'Bishop International Airport', FALSE, TRUE),
('FSD', 'Sioux Falls', 'Joe Foss Field', FALSE, TRUE),
('FWA', 'Fort Wayne', 'Fort Wayne International Airport', FALSE, TRUE),
('GEG', 'Spokane', 'Spokane International Airport', FALSE, TRUE),
('GFK', 'Grand Forks', 'Grand Forks International Airport', FALSE, TRUE),
('GJT', 'Grand Junction', 'Grand Junction Regional Airport', FALSE, TRUE),
('GPT', 'Gulfport', 'Gulfport-Biloxi International Airport', FALSE, TRUE),
('GRB', 'Green Bay', 'Green Bay/Austin Straubel International Airport', FALSE, TRUE),
('GRI', 'Grand Island', 'Grand Island Central Nebraska Regional Airport', FALSE, TRUE),
('GRR', 'Grand Rapids', 'Gerald R. Ford International Airport', FALSE, TRUE),
('GSO', 'Greensboro', 'Greensboro-High Point International Airport', FALSE, TRUE),
('GSP', 'Greenville-Spartanburg', 'Greenville-Spartanburg International Airport', FALSE, TRUE),
('GTF', 'Great Falls', 'Great Falls International Airport', FALSE, TRUE),
('HDN', 'Hayden', 'Hayden-Yampa Valley Regional Airport', FALSE, TRUE),
('HHH', 'Hilton Head', 'Hilton Head Airport', FALSE, TRUE),
('HLN', 'Helena', 'Helena Regional Airport', FALSE, TRUE),
('HNL', 'Honolulu', 'Daniel K. Inouye International Airport', FALSE, TRUE),
('HOB', 'Hobbs', 'Lea County Regional Airport', FALSE, TRUE),
('HPN', 'White Plains', 'Westchester County Airport', FALSE, TRUE),
('HRL', 'Harlingen', 'Harlingen/Rio Grande Valley International Airport', FALSE, TRUE),
('HSV', 'Huntsville', 'Huntsville International Airport', FALSE, TRUE),
('IAG', 'Niagara Falls', 'Niagara Falls International Airport', FALSE, TRUE),
('ICT', 'Wichita', 'Wichita Dwight D. Eisenhower National Airport', FALSE, TRUE),
('IDA', 'Idaho Falls', 'Idaho Falls Regional Airport', FALSE, TRUE),
('ILM', 'Wilmington', 'Wilmington International Airport', FALSE, TRUE),
('JAC', 'Jackson', 'Jackson Hole Airport', FALSE, TRUE),
('JAN', 'Jackson', 'Jackson-Medgar Wiley Kemp International Airport', FALSE, TRUE),
('LBB', 'Lubbock', 'Lubbock Preston Smith International Airport', FALSE, TRUE),
('LCH', 'Lake Charles', 'Lake Charles Regional Airport', FALSE, TRUE),
('LCK', 'Columbus', 'Ohio State University Airport', FALSE, TRUE),
('LEX', 'Lexington', 'Lexington Blue Grass Airport', FALSE, TRUE),
('LFT', 'Lafayette', 'Lafayette Regional Airport', FALSE, TRUE),
('LIT', 'Little Rock', 'Bill and Hillary Clinton National Airport', FALSE, TRUE),
('LNK', 'Lincoln', 'Lincoln Airport', FALSE, TRUE),
('LRD', 'Laredo', 'Laredo International Airport', FALSE, TRUE),
('MAF', 'Midland', 'Midland International Air and Space Port', FALSE, TRUE),
('MDT', 'Harrisburg', 'Harrisburg International Airport', FALSE, TRUE),
('MFE', 'McAllen', 'McAllen-Miller International Airport', FALSE, TRUE),
('MFR', 'Medford', 'Medford-Jackson County Airport', FALSE, TRUE),
('MHT', 'Manchester', 'Manchester-Boston Regional Airport', FALSE, TRUE),
('MLB', 'Melbourne', 'Melbourne International Airport', FALSE, TRUE),
('MLI', 'Moline', 'Quad City International Airport', FALSE, TRUE),
('MOB', 'Mobile', 'Mobile Regional Airport', FALSE, TRUE),
('MOT', 'Minot', 'Minot International Airport', FALSE, TRUE),
('MRY', 'Monterey', 'Monterey Regional Airport', FALSE, TRUE),
('MSN', 'Madison', 'Dane County Regional Airport', FALSE, TRUE),
('MSO', 'Missoula', 'Missoula International Airport', FALSE, TRUE),
('MTJ', 'Montrose', 'Montrose Regional Airport', FALSE, TRUE),
('MVY', 'Martha''s Vineyard', 'Martha''s Vineyard Airport', FALSE, TRUE),
('MYR', 'Myrtle Beach', 'Myrtle Beach International Airport', FALSE, TRUE),
('OGG', 'Maui', 'Kahului Airport', FALSE, TRUE),
('OKC', 'Oklahoma City', 'Oklahoma City International Airport', FALSE, TRUE),
('ORF', 'Norfolk', 'Norfolk International Airport', FALSE, TRUE),
('ORH', 'Worcester', 'Worcester Regional Airport', FALSE, TRUE),
('OTH', 'North Bend', 'North Bend Airport', FALSE, TRUE),
('PBG', 'Plattsburgh', 'Plattsburgh International Airport', FALSE, TRUE),
('PGD', 'Punta Gorda', 'Punta Gorda Airport', FALSE, TRUE),
('PIA', 'Peoria', 'General Downing-Peoria International Airport', FALSE, TRUE),
('PIE', 'St. Petersburg', 'St. Petersburg-Clearwater International Airport', FALSE, TRUE),
('PNS', 'Pensacola', 'Pensacola International Airport', FALSE, TRUE),
('PSC', 'Pasco', 'Tri-Cities Airport', FALSE, TRUE),
('PSM', 'Portsmouth', 'Pease Air National Guard Base', FALSE, TRUE),
('PSP', 'Palm Springs', 'Palm Springs International Airport', FALSE, TRUE),
('PVD', 'Providence', 'Theodore Francis Green State Airport', FALSE, TRUE),
('PVU', 'Provo', 'Provo Municipal Airport', FALSE, TRUE),
('PWM', 'Portland', 'Portland International Jetport', FALSE, TRUE),
('RAP', 'Rapid City', 'Rapid City Regional Airport', FALSE, TRUE),
('RDD', 'Redding', 'Redding Regional Airport', FALSE, TRUE),
('RDM', 'Redmond', 'Roberts Field', FALSE, TRUE),
('RFD', 'Rockford', 'Chicago Rockford International Airport', FALSE, TRUE),
('RIC', 'Richmond', 'Richmond International Airport', FALSE, TRUE),
('ROA', 'Roanoke', 'Roanoke-Blacksburg Regional Airport', FALSE, TRUE),
('ROC', 'Rochester', 'Rochester International Airport', FALSE, TRUE),
('RST', 'Rochester', 'Rochester International Airport', FALSE, TRUE),
('SAF', 'Santa Fe', 'Santa Fe Regional Airport', FALSE, TRUE),
('SAV', 'Savannah', 'Savannah/Hilton Head International Airport', FALSE, TRUE),
('SBA', 'Santa Barbara', 'Santa Barbara Airport', FALSE, TRUE),
('SBN', 'South Bend', 'South Bend International Airport', FALSE, TRUE),
('SBP', 'San Luis Obispo', 'San Luis Obispo County Regional Airport', FALSE, TRUE),
('SCE', 'State College', 'University Park Airport', FALSE, TRUE),
('SCK', 'Stockton', 'Stockton Metropolitan Airport', FALSE, TRUE),
('SDF', 'Louisville', 'Louisville International Airport', FALSE, TRUE),
('SFB', 'Sanford', 'Orlando Sanford International Airport', FALSE, TRUE),
('SGF', 'Springfield', 'Springfield-Branson National Airport', FALSE, TRUE),
('SGU', 'St. George', 'St. George Regional Airport', FALSE, TRUE),
('SHV', 'Shreveport', 'Shreveport Regional Airport', FALSE, TRUE),
('SMX', 'Santa Maria', 'Santa Maria Public Airport', FALSE, TRUE),
('SRQ', 'Sarasota', 'Sarasota-Bradenton International Airport', FALSE, TRUE),
('SYR', 'Syracuse', 'Syracuse Hancock International Airport', FALSE, TRUE),
('TUL', 'Tulsa', 'Tulsa International Airport', FALSE, TRUE),
('TUS', 'Tucson', 'Tucson International Airport', FALSE, TRUE),
('TVC', 'Traverse City', 'Cherry Capital Airport', FALSE, TRUE),
('TYS', 'Knoxville', 'McGhee Tyson Air National Guard Base', FALSE, TRUE),
('USA', 'Sumter', 'Sumter Metropolitan Airport', FALSE, TRUE),
('VPS', 'Fort Walton Beach', 'Fort Walton Beach-Destin Airport', FALSE, TRUE),
('XNA', 'Bentonville', 'Northwest Arkansas Regional Airport', FALSE, TRUE),
('XWA', 'Phoenix', 'Goodyear Regional Airport', FALSE, TRUE);
